# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pubkey.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='pubkey.proto',
  package='zsearch',
  syntax='proto3',
  serialized_pb=_b('\n\x0cpubkey.proto\x12\x07zsearch\x1a\x0c\x63ommon.proto\"N\n\x13RSACryptographicKey\x12\x0f\n\x07modulus\x18\x01 \x01(\x0c\x12\x10\n\x08\x65xponent\x18\x02 \x01(\x0c\x12\t\n\x01p\x18\x03 \x01(\x0c\x12\t\n\x01q\x18\x04 \x01(\x0c\"L\n\x13\x44SACryptographicKey\x12\t\n\x01p\x18\x01 \x01(\x0c\x12\t\n\x01q\x18\x02 \x01(\x0c\x12\t\n\x01g\x18\x03 \x01(\x0c\x12\t\n\x01y\x18\x04 \x01(\x0c\x12\t\n\x01x\x18\x05 \x01(\x0c\"K\n\x13\x45\x43\x43\x43ryptographicKey\x12\r\n\x05\x63urve\x18\x01 \x01(\r\x12\t\n\x01x\x18\x02 \x01(\x0c\x12\t\n\x01y\x18\x03 \x01(\x0c\x12\x0f\n\x07private\x18\x04 \x01(\x0c\"\xc8\x02\n\x10\x43ryptographicKey\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.zsearch.CryptographicKey.KeyType\x12+\n\x03rsa\x18\x02 \x01(\x0b\x32\x1c.zsearch.RSACryptographicKeyH\x00\x12+\n\x03\x64sa\x18\x03 \x01(\x0b\x32\x1c.zsearch.DSACryptographicKeyH\x00\x12+\n\x03\x65\x63\x63\x18\x04 \x01(\x0b\x32\x1c.zsearch.ECCCryptographicKeyH\x00\x12\x0e\n\x06\x62roken\x18\x05 \x01(\x08\x12\x0e\n\x06\x63ommon\x18\x06 \x01(\x08\x12\x0e\n\x06\x64\x65\x62ian\x18\x07 \x01(\x08\"?\n\x07KeyType\x12\x0c\n\x08RESERVED\x10\x00\x12\x0b\n\x07UNKNOWN\x10\x01\x12\x07\n\x03RSA\x10\x02\x12\x07\n\x03\x44SA\x10\x03\x12\x07\n\x03\x45\x43\x43\x10\x04\x42\x0b\n\tkey_oneofb\x06proto3')
  ,
  dependencies=[common__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)



_CRYPTOGRAPHICKEY_KEYTYPE = _descriptor.EnumDescriptor(
  name='KeyType',
  full_name='zsearch.CryptographicKey.KeyType',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='RESERVED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='RSA', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DSA', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='ECC', index=4, number=4,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=527,
  serialized_end=590,
)
_sym_db.RegisterEnumDescriptor(_CRYPTOGRAPHICKEY_KEYTYPE)


_RSACRYPTOGRAPHICKEY = _descriptor.Descriptor(
  name='RSACryptographicKey',
  full_name='zsearch.RSACryptographicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='modulus', full_name='zsearch.RSACryptographicKey.modulus', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='exponent', full_name='zsearch.RSACryptographicKey.exponent', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='p', full_name='zsearch.RSACryptographicKey.p', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='q', full_name='zsearch.RSACryptographicKey.q', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=117,
)


_DSACRYPTOGRAPHICKEY = _descriptor.Descriptor(
  name='DSACryptographicKey',
  full_name='zsearch.DSACryptographicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='zsearch.DSACryptographicKey.p', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='q', full_name='zsearch.DSACryptographicKey.q', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='g', full_name='zsearch.DSACryptographicKey.g', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='zsearch.DSACryptographicKey.y', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='zsearch.DSACryptographicKey.x', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=195,
)


_ECCCRYPTOGRAPHICKEY = _descriptor.Descriptor(
  name='ECCCryptographicKey',
  full_name='zsearch.ECCCryptographicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='curve', full_name='zsearch.ECCCryptographicKey.curve', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='x', full_name='zsearch.ECCCryptographicKey.x', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='zsearch.ECCCryptographicKey.y', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='private', full_name='zsearch.ECCCryptographicKey.private', index=3,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=197,
  serialized_end=272,
)


_CRYPTOGRAPHICKEY = _descriptor.Descriptor(
  name='CryptographicKey',
  full_name='zsearch.CryptographicKey',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='zsearch.CryptographicKey.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rsa', full_name='zsearch.CryptographicKey.rsa', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='dsa', full_name='zsearch.CryptographicKey.dsa', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='ecc', full_name='zsearch.CryptographicKey.ecc', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='broken', full_name='zsearch.CryptographicKey.broken', index=4,
      number=5, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='common', full_name='zsearch.CryptographicKey.common', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='debian', full_name='zsearch.CryptographicKey.debian', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CRYPTOGRAPHICKEY_KEYTYPE,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='key_oneof', full_name='zsearch.CryptographicKey.key_oneof',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=275,
  serialized_end=603,
)

_CRYPTOGRAPHICKEY.fields_by_name['type'].enum_type = _CRYPTOGRAPHICKEY_KEYTYPE
_CRYPTOGRAPHICKEY.fields_by_name['rsa'].message_type = _RSACRYPTOGRAPHICKEY
_CRYPTOGRAPHICKEY.fields_by_name['dsa'].message_type = _DSACRYPTOGRAPHICKEY
_CRYPTOGRAPHICKEY.fields_by_name['ecc'].message_type = _ECCCRYPTOGRAPHICKEY
_CRYPTOGRAPHICKEY_KEYTYPE.containing_type = _CRYPTOGRAPHICKEY
_CRYPTOGRAPHICKEY.oneofs_by_name['key_oneof'].fields.append(
  _CRYPTOGRAPHICKEY.fields_by_name['rsa'])
_CRYPTOGRAPHICKEY.fields_by_name['rsa'].containing_oneof = _CRYPTOGRAPHICKEY.oneofs_by_name['key_oneof']
_CRYPTOGRAPHICKEY.oneofs_by_name['key_oneof'].fields.append(
  _CRYPTOGRAPHICKEY.fields_by_name['dsa'])
_CRYPTOGRAPHICKEY.fields_by_name['dsa'].containing_oneof = _CRYPTOGRAPHICKEY.oneofs_by_name['key_oneof']
_CRYPTOGRAPHICKEY.oneofs_by_name['key_oneof'].fields.append(
  _CRYPTOGRAPHICKEY.fields_by_name['ecc'])
_CRYPTOGRAPHICKEY.fields_by_name['ecc'].containing_oneof = _CRYPTOGRAPHICKEY.oneofs_by_name['key_oneof']
DESCRIPTOR.message_types_by_name['RSACryptographicKey'] = _RSACRYPTOGRAPHICKEY
DESCRIPTOR.message_types_by_name['DSACryptographicKey'] = _DSACRYPTOGRAPHICKEY
DESCRIPTOR.message_types_by_name['ECCCryptographicKey'] = _ECCCRYPTOGRAPHICKEY
DESCRIPTOR.message_types_by_name['CryptographicKey'] = _CRYPTOGRAPHICKEY

RSACryptographicKey = _reflection.GeneratedProtocolMessageType('RSACryptographicKey', (_message.Message,), dict(
  DESCRIPTOR = _RSACRYPTOGRAPHICKEY,
  __module__ = 'pubkey_pb2'
  # @@protoc_insertion_point(class_scope:zsearch.RSACryptographicKey)
  ))
_sym_db.RegisterMessage(RSACryptographicKey)

DSACryptographicKey = _reflection.GeneratedProtocolMessageType('DSACryptographicKey', (_message.Message,), dict(
  DESCRIPTOR = _DSACRYPTOGRAPHICKEY,
  __module__ = 'pubkey_pb2'
  # @@protoc_insertion_point(class_scope:zsearch.DSACryptographicKey)
  ))
_sym_db.RegisterMessage(DSACryptographicKey)

ECCCryptographicKey = _reflection.GeneratedProtocolMessageType('ECCCryptographicKey', (_message.Message,), dict(
  DESCRIPTOR = _ECCCRYPTOGRAPHICKEY,
  __module__ = 'pubkey_pb2'
  # @@protoc_insertion_point(class_scope:zsearch.ECCCryptographicKey)
  ))
_sym_db.RegisterMessage(ECCCryptographicKey)

CryptographicKey = _reflection.GeneratedProtocolMessageType('CryptographicKey', (_message.Message,), dict(
  DESCRIPTOR = _CRYPTOGRAPHICKEY,
  __module__ = 'pubkey_pb2'
  # @@protoc_insertion_point(class_scope:zsearch.CryptographicKey)
  ))
_sym_db.RegisterMessage(CryptographicKey)


# @@protoc_insertion_point(module_scope)
