// Code generated by protoc-gen-go.
// source: certificate.proto
// DO NOT EDIT!

package censys_definitions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CertificateType int32

const (
	CertificateType_CERTIFICATE_TYPE_RESERVED     CertificateType = 0
	CertificateType_CERTIFICATE_TYPE_UNKNOWN      CertificateType = 1
	CertificateType_CERTIFICATE_TYPE_LEAF         CertificateType = 2
	CertificateType_CERTIFICATE_TYPE_INTERMEDIATE CertificateType = 3
	CertificateType_CERTIFICATE_TYPE_ROOT         CertificateType = 4
)

var CertificateType_name = map[int32]string{
	0: "CERTIFICATE_TYPE_RESERVED",
	1: "CERTIFICATE_TYPE_UNKNOWN",
	2: "CERTIFICATE_TYPE_LEAF",
	3: "CERTIFICATE_TYPE_INTERMEDIATE",
	4: "CERTIFICATE_TYPE_ROOT",
}
var CertificateType_value = map[string]int32{
	"CERTIFICATE_TYPE_RESERVED":     0,
	"CERTIFICATE_TYPE_UNKNOWN":      1,
	"CERTIFICATE_TYPE_LEAF":         2,
	"CERTIFICATE_TYPE_INTERMEDIATE": 3,
	"CERTIFICATE_TYPE_ROOT":         4,
}

func (x CertificateType) String() string {
	return proto.EnumName(CertificateType_name, int32(x))
}
func (CertificateType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type CertificateSource int32

const (
	CertificateSource_CERTIFICATE_SOURCE_RESERVED           CertificateSource = 0
	CertificateSource_CERTIFICATE_SOURCE_UNKNOWN            CertificateSource = 1
	CertificateSource_CERTIFICATE_SOURCE_SCAN               CertificateSource = 2
	CertificateSource_CERTIFICATE_SOURCE_CT                 CertificateSource = 3
	CertificateSource_CERTIFICATE_SOURCE_MOZILLA_SALESFORCE CertificateSource = 4
	CertificateSource_CERTIFICATE_SOURCE_RESEARCH           CertificateSource = 5
	CertificateSource_CERTIFICATE_SOURCE_RAPID7             CertificateSource = 6
	CertificateSource_CERTIFICATE_SOURCE_HUBBLE             CertificateSource = 7
	CertificateSource_CERTIFICATE_SOURCE_CT_CHAIN           CertificateSource = 8
)

var CertificateSource_name = map[int32]string{
	0: "CERTIFICATE_SOURCE_RESERVED",
	1: "CERTIFICATE_SOURCE_UNKNOWN",
	2: "CERTIFICATE_SOURCE_SCAN",
	3: "CERTIFICATE_SOURCE_CT",
	4: "CERTIFICATE_SOURCE_MOZILLA_SALESFORCE",
	5: "CERTIFICATE_SOURCE_RESEARCH",
	6: "CERTIFICATE_SOURCE_RAPID7",
	7: "CERTIFICATE_SOURCE_HUBBLE",
	8: "CERTIFICATE_SOURCE_CT_CHAIN",
}
var CertificateSource_value = map[string]int32{
	"CERTIFICATE_SOURCE_RESERVED":           0,
	"CERTIFICATE_SOURCE_UNKNOWN":            1,
	"CERTIFICATE_SOURCE_SCAN":               2,
	"CERTIFICATE_SOURCE_CT":                 3,
	"CERTIFICATE_SOURCE_MOZILLA_SALESFORCE": 4,
	"CERTIFICATE_SOURCE_RESEARCH":           5,
	"CERTIFICATE_SOURCE_RAPID7":             6,
	"CERTIFICATE_SOURCE_HUBBLE":             7,
	"CERTIFICATE_SOURCE_CT_CHAIN":           8,
}

func (x CertificateSource) String() string {
	return proto.EnumName(CertificateSource_name, int32(x))
}
func (CertificateSource) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type CertificateParseStatus int32

const (
	CertificateParseStatus_CERTIFICATE_PARSE_STATUS_RESERVED   CertificateParseStatus = 0
	CertificateParseStatus_CERTIFICATE_PARSE_STATUS_UNKNOWN    CertificateParseStatus = 1
	CertificateParseStatus_CERTIFICATE_PARSE_STATUS_SUCCESS    CertificateParseStatus = 2
	CertificateParseStatus_CERTIFICATE_PARSE_STATUS_FAIL       CertificateParseStatus = 3
	CertificateParseStatus_CERTIFICATE_PARSE_STATUS_NOT_PARSED CertificateParseStatus = 4
)

var CertificateParseStatus_name = map[int32]string{
	0: "CERTIFICATE_PARSE_STATUS_RESERVED",
	1: "CERTIFICATE_PARSE_STATUS_UNKNOWN",
	2: "CERTIFICATE_PARSE_STATUS_SUCCESS",
	3: "CERTIFICATE_PARSE_STATUS_FAIL",
	4: "CERTIFICATE_PARSE_STATUS_NOT_PARSED",
}
var CertificateParseStatus_value = map[string]int32{
	"CERTIFICATE_PARSE_STATUS_RESERVED":   0,
	"CERTIFICATE_PARSE_STATUS_UNKNOWN":    1,
	"CERTIFICATE_PARSE_STATUS_SUCCESS":    2,
	"CERTIFICATE_PARSE_STATUS_FAIL":       3,
	"CERTIFICATE_PARSE_STATUS_NOT_PARSED": 4,
}

func (x CertificateParseStatus) String() string {
	return proto.EnumName(CertificateParseStatus_name, int32(x))
}
func (CertificateParseStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type CertificateRevocationReason int32

const (
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_RESERVED CertificateRevocationReason = 0
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_UNKNOWN  CertificateRevocationReason = 1
	// RFC 5280
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_UNSPECIFIED            CertificateRevocationReason = 2
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_KEY_COMPROMISE         CertificateRevocationReason = 3
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_CA_COMPROMISE          CertificateRevocationReason = 4
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_AFFILIATION_CHANGED    CertificateRevocationReason = 5
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_SUPERSEDED             CertificateRevocationReason = 6
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_CESSATION_OF_OPERATION CertificateRevocationReason = 7
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_CERTIFICATE_HOLD       CertificateRevocationReason = 8
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_REMOVE_FROM_CRL        CertificateRevocationReason = 9
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_PRIVILEGE_WITHDRAWN    CertificateRevocationReason = 10
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_AA_COMPROMISE          CertificateRevocationReason = 11
)

var CertificateRevocationReason_name = map[int32]string{
	0:  "CERTIFICATE_REVOCATION_REASON_RESERVED",
	1:  "CERTIFICATE_REVOCATION_REASON_UNKNOWN",
	2:  "CERTIFICATE_REVOCATION_REASON_UNSPECIFIED",
	3:  "CERTIFICATE_REVOCATION_REASON_KEY_COMPROMISE",
	4:  "CERTIFICATE_REVOCATION_REASON_CA_COMPROMISE",
	5:  "CERTIFICATE_REVOCATION_REASON_AFFILIATION_CHANGED",
	6:  "CERTIFICATE_REVOCATION_REASON_SUPERSEDED",
	7:  "CERTIFICATE_REVOCATION_REASON_CESSATION_OF_OPERATION",
	8:  "CERTIFICATE_REVOCATION_REASON_CERTIFICATE_HOLD",
	9:  "CERTIFICATE_REVOCATION_REASON_REMOVE_FROM_CRL",
	10: "CERTIFICATE_REVOCATION_REASON_PRIVILEGE_WITHDRAWN",
	11: "CERTIFICATE_REVOCATION_REASON_AA_COMPROMISE",
}
var CertificateRevocationReason_value = map[string]int32{
	"CERTIFICATE_REVOCATION_REASON_RESERVED":               0,
	"CERTIFICATE_REVOCATION_REASON_UNKNOWN":                1,
	"CERTIFICATE_REVOCATION_REASON_UNSPECIFIED":            2,
	"CERTIFICATE_REVOCATION_REASON_KEY_COMPROMISE":         3,
	"CERTIFICATE_REVOCATION_REASON_CA_COMPROMISE":          4,
	"CERTIFICATE_REVOCATION_REASON_AFFILIATION_CHANGED":    5,
	"CERTIFICATE_REVOCATION_REASON_SUPERSEDED":             6,
	"CERTIFICATE_REVOCATION_REASON_CESSATION_OF_OPERATION": 7,
	"CERTIFICATE_REVOCATION_REASON_CERTIFICATE_HOLD":       8,
	"CERTIFICATE_REVOCATION_REASON_REMOVE_FROM_CRL":        9,
	"CERTIFICATE_REVOCATION_REASON_PRIVILEGE_WITHDRAWN":    10,
	"CERTIFICATE_REVOCATION_REASON_AA_COMPROMISE":          11,
}

func (x CertificateRevocationReason) String() string {
	return proto.EnumName(CertificateRevocationReason_name, int32(x))
}
func (CertificateRevocationReason) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type RootStoreStatus struct {
	// (trusted path || whitelisted) && other certificate validation (e.g., expiration)
	Valid bool `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	// was certificate ever valid in the past?
	WasValid bool `protobuf:"varint,2,opt,name=was_valid,json=wasValid" json:"was_valid,omitempty"`
	// does there exist a path from the certificate to the root store
	TrustedPath    bool `protobuf:"varint,3,opt,name=trusted_path,json=trustedPath" json:"trusted_path,omitempty"`
	WasTrustedPath bool `protobuf:"varint,4,opt,name=was_trusted_path,json=wasTrustedPath" json:"was_trusted_path,omitempty"`
	// is the certificate explicitly blacklisted by the browser (e.g., OneCRL)
	Blacklisted bool            `protobuf:"varint,5,opt,name=blacklisted" json:"blacklisted,omitempty"`
	Whitelisted bool            `protobuf:"varint,6,opt,name=whitelisted" json:"whitelisted,omitempty"`
	Type        CertificateType `protobuf:"varint,7,opt,name=type,enum=censys_definitions.CertificateType" json:"type,omitempty"`
	// contains sha256fp of path to root store
	Path [][]byte `protobuf:"bytes,8,rep,name=path,proto3" json:"path,omitempty"`
}

func (m *RootStoreStatus) Reset()                    { *m = RootStoreStatus{} }
func (m *RootStoreStatus) String() string            { return proto.CompactTextString(m) }
func (*RootStoreStatus) ProtoMessage()               {}
func (*RootStoreStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *RootStoreStatus) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *RootStoreStatus) GetWasValid() bool {
	if m != nil {
		return m.WasValid
	}
	return false
}

func (m *RootStoreStatus) GetTrustedPath() bool {
	if m != nil {
		return m.TrustedPath
	}
	return false
}

func (m *RootStoreStatus) GetWasTrustedPath() bool {
	if m != nil {
		return m.WasTrustedPath
	}
	return false
}

func (m *RootStoreStatus) GetBlacklisted() bool {
	if m != nil {
		return m.Blacklisted
	}
	return false
}

func (m *RootStoreStatus) GetWhitelisted() bool {
	if m != nil {
		return m.Whitelisted
	}
	return false
}

func (m *RootStoreStatus) GetType() CertificateType {
	if m != nil {
		return m.Type
	}
	return CertificateType_CERTIFICATE_TYPE_RESERVED
}

func (m *RootStoreStatus) GetPath() [][]byte {
	if m != nil {
		return m.Path
	}
	return nil
}

type CertificateValidation struct {
	Nss       *RootStoreStatus `protobuf:"bytes,1,opt,name=nss" json:"nss,omitempty"`
	Microsoft *RootStoreStatus `protobuf:"bytes,2,opt,name=microsoft" json:"microsoft,omitempty"`
	Apple     *RootStoreStatus `protobuf:"bytes,3,opt,name=apple" json:"apple,omitempty"`
	Java      *RootStoreStatus `protobuf:"bytes,4,opt,name=java" json:"java,omitempty"`
	Android   *RootStoreStatus `protobuf:"bytes,5,opt,name=android" json:"android,omitempty"`
	// also track for Google CT servers so we know what to push
	GoogleCtPrimary *RootStoreStatus `protobuf:"bytes,10,opt,name=google_ct_primary,json=googleCtPrimary" json:"google_ct_primary,omitempty"`
}

func (m *CertificateValidation) Reset()                    { *m = CertificateValidation{} }
func (m *CertificateValidation) String() string            { return proto.CompactTextString(m) }
func (*CertificateValidation) ProtoMessage()               {}
func (*CertificateValidation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *CertificateValidation) GetNss() *RootStoreStatus {
	if m != nil {
		return m.Nss
	}
	return nil
}

func (m *CertificateValidation) GetMicrosoft() *RootStoreStatus {
	if m != nil {
		return m.Microsoft
	}
	return nil
}

func (m *CertificateValidation) GetApple() *RootStoreStatus {
	if m != nil {
		return m.Apple
	}
	return nil
}

func (m *CertificateValidation) GetJava() *RootStoreStatus {
	if m != nil {
		return m.Java
	}
	return nil
}

func (m *CertificateValidation) GetAndroid() *RootStoreStatus {
	if m != nil {
		return m.Android
	}
	return nil
}

func (m *CertificateValidation) GetGoogleCtPrimary() *RootStoreStatus {
	if m != nil {
		return m.GoogleCtPrimary
	}
	return nil
}

type MozillaSalesForceStatus struct {
	CurrentIn                      bool   `protobuf:"varint,1,opt,name=current_in,json=currentIn" json:"current_in,omitempty"`
	WasIn                          bool   `protobuf:"varint,2,opt,name=was_in,json=wasIn" json:"was_in,omitempty"`
	OwnerName                      string `protobuf:"bytes,3,opt,name=owner_name,json=ownerName" json:"owner_name,omitempty"`
	ParentName                     string `protobuf:"bytes,4,opt,name=parent_name,json=parentName" json:"parent_name,omitempty"`
	CertificateName                string `protobuf:"bytes,5,opt,name=certificate_name,json=certificateName" json:"certificate_name,omitempty"`
	CertificatePolicy              string `protobuf:"bytes,6,opt,name=certificate_policy,json=certificatePolicy" json:"certificate_policy,omitempty"`
	CertificationPracticeStatement string `protobuf:"bytes,7,opt,name=certification_practice_statement,json=certificationPracticeStatement" json:"certification_practice_statement,omitempty"`
	CpSameAsParent                 bool   `protobuf:"varint,8,opt,name=cp_same_as_parent,json=cpSameAsParent" json:"cp_same_as_parent,omitempty"`
	AuditSameAsParent              bool   `protobuf:"varint,9,opt,name=audit_same_as_parent,json=auditSameAsParent" json:"audit_same_as_parent,omitempty"`
	StandardAudit                  string `protobuf:"bytes,10,opt,name=standard_audit,json=standardAudit" json:"standard_audit,omitempty"`
	BrAudit                        string `protobuf:"bytes,11,opt,name=br_audit,json=brAudit" json:"br_audit,omitempty"`
	Auditor                        string `protobuf:"bytes,12,opt,name=auditor" json:"auditor,omitempty"`
}

func (m *MozillaSalesForceStatus) Reset()                    { *m = MozillaSalesForceStatus{} }
func (m *MozillaSalesForceStatus) String() string            { return proto.CompactTextString(m) }
func (*MozillaSalesForceStatus) ProtoMessage()               {}
func (*MozillaSalesForceStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *MozillaSalesForceStatus) GetCurrentIn() bool {
	if m != nil {
		return m.CurrentIn
	}
	return false
}

func (m *MozillaSalesForceStatus) GetWasIn() bool {
	if m != nil {
		return m.WasIn
	}
	return false
}

func (m *MozillaSalesForceStatus) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetParentName() string {
	if m != nil {
		return m.ParentName
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetCertificateName() string {
	if m != nil {
		return m.CertificateName
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetCertificatePolicy() string {
	if m != nil {
		return m.CertificatePolicy
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetCertificationPracticeStatement() string {
	if m != nil {
		return m.CertificationPracticeStatement
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetCpSameAsParent() bool {
	if m != nil {
		return m.CpSameAsParent
	}
	return false
}

func (m *MozillaSalesForceStatus) GetAuditSameAsParent() bool {
	if m != nil {
		return m.AuditSameAsParent
	}
	return false
}

func (m *MozillaSalesForceStatus) GetStandardAudit() string {
	if m != nil {
		return m.StandardAudit
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetBrAudit() string {
	if m != nil {
		return m.BrAudit
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetAuditor() string {
	if m != nil {
		return m.Auditor
	}
	return ""
}

type CertificateRevocation struct {
	Revoked bool                        `protobuf:"varint,1,opt,name=revoked" json:"revoked,omitempty"`
	Reason  CertificateRevocationReason `protobuf:"varint,2,opt,name=reason,enum=censys_definitions.CertificateRevocationReason" json:"reason,omitempty"`
}

func (m *CertificateRevocation) Reset()                    { *m = CertificateRevocation{} }
func (m *CertificateRevocation) String() string            { return proto.CompactTextString(m) }
func (*CertificateRevocation) ProtoMessage()               {}
func (*CertificateRevocation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *CertificateRevocation) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *CertificateRevocation) GetReason() CertificateRevocationReason {
	if m != nil {
		return m.Reason
	}
	return CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_RESERVED
}

type CertificateAudit struct {
	Mozilla *MozillaSalesForceStatus `protobuf:"bytes,1,opt,name=mozilla" json:"mozilla,omitempty"`
}

func (m *CertificateAudit) Reset()                    { *m = CertificateAudit{} }
func (m *CertificateAudit) String() string            { return proto.CompactTextString(m) }
func (*CertificateAudit) ProtoMessage()               {}
func (*CertificateAudit) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *CertificateAudit) GetMozilla() *MozillaSalesForceStatus {
	if m != nil {
		return m.Mozilla
	}
	return nil
}

// Database Records
type Certificate struct {
	Sha1Fp       []byte                 `protobuf:"bytes,1,opt,name=sha1fp,proto3" json:"sha1fp,omitempty"`
	Sha256Fp     []byte                 `protobuf:"bytes,2,opt,name=sha256fp,proto3" json:"sha256fp,omitempty"`
	Raw          []byte                 `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	Parsed       string                 `protobuf:"bytes,4,opt,name=parsed" json:"parsed,omitempty"`
	ParseStatus  CertificateParseStatus `protobuf:"varint,44,opt,name=parse_status,json=parseStatus,enum=censys_definitions.CertificateParseStatus" json:"parse_status,omitempty"`
	ParseVersion uint32                 `protobuf:"varint,39,opt,name=parse_version,json=parseVersion" json:"parse_version,omitempty"`
	ParseError   string                 `protobuf:"bytes,47,opt,name=parse_error,json=parseError" json:"parse_error,omitempty"`
	Parents      [][]byte               `protobuf:"bytes,5,rep,name=parents,proto3" json:"parents,omitempty"`
	// the chain that we received with the certificate and pass
	// to the certificate processing daemon.
	PresentedChain       [][]byte               `protobuf:"bytes,45,rep,name=presented_chain,json=presentedChain,proto3" json:"presented_chain,omitempty"`
	Source               CertificateSource      `protobuf:"varint,28,opt,name=source,enum=censys_definitions.CertificateSource" json:"source,omitempty"`
	SeenInScan           bool                   `protobuf:"varint,29,opt,name=seen_in_scan,json=seenInScan" json:"seen_in_scan,omitempty"`
	PostProcessed        bool                   `protobuf:"varint,26,opt,name=post_processed,json=postProcessed" json:"post_processed,omitempty"`
	PostProcessTimestamp uint32                 `protobuf:"varint,37,opt,name=post_process_timestamp,json=postProcessTimestamp" json:"post_process_timestamp,omitempty"`
	Validation           *CertificateValidation `protobuf:"bytes,35,opt,name=validation" json:"validation,omitempty"`
	Ct                   *CTStatus              `protobuf:"bytes,30,opt,name=ct" json:"ct,omitempty"`
	Zlint                *ZLint                 `protobuf:"bytes,38,opt,name=zlint" json:"zlint,omitempty"`
	Revocation           *CertificateRevocation `protobuf:"bytes,43,opt,name=revocation" json:"revocation,omitempty"`
	Audit                *CertificateAudit      `protobuf:"bytes,46,opt,name=audit" json:"audit,omitempty"`
	// store wheter record is precert so that CT synchronization
	// daemon can quickly decide what to do without reparsing the
	// raw certificate
	IsPrecert bool `protobuf:"varint,32,opt,name=is_precert,json=isPrecert" json:"is_precert,omitempty"`
	// store time range that certificate is valid so that cert
	// dump job can mark certificates as expired
	NotValidAfter         uint32                   `protobuf:"varint,41,opt,name=not_valid_after,json=notValidAfter" json:"not_valid_after,omitempty"`
	NotValidBefore        uint32                   `protobuf:"varint,42,opt,name=not_valid_before,json=notValidBefore" json:"not_valid_before,omitempty"`
	InNss                 bool                     `protobuf:"varint,6,opt,name=in_nss,json=inNss" json:"in_nss,omitempty"`
	InMicrosoft           bool                     `protobuf:"varint,7,opt,name=in_microsoft,json=inMicrosoft" json:"in_microsoft,omitempty"`
	InApple               bool                     `protobuf:"varint,8,opt,name=in_apple,json=inApple" json:"in_apple,omitempty"`
	ValidationTimestamp   uint32                   `protobuf:"varint,10,opt,name=validation_timestamp,json=validationTimestamp" json:"validation_timestamp,omitempty"`
	ValidNss              bool                     `protobuf:"varint,11,opt,name=valid_nss,json=validNss" json:"valid_nss,omitempty"`
	ValidMicrosoft        bool                     `protobuf:"varint,12,opt,name=valid_microsoft,json=validMicrosoft" json:"valid_microsoft,omitempty"`
	ValidApple            bool                     `protobuf:"varint,13,opt,name=valid_apple,json=validApple" json:"valid_apple,omitempty"`
	WasValidNss           bool                     `protobuf:"varint,14,opt,name=was_valid_nss,json=wasValidNss" json:"was_valid_nss,omitempty"`
	WasValidMicrosoft     bool                     `protobuf:"varint,15,opt,name=was_valid_microsoft,json=wasValidMicrosoft" json:"was_valid_microsoft,omitempty"`
	WasValidApple         bool                     `protobuf:"varint,16,opt,name=was_valid_apple,json=wasValidApple" json:"was_valid_apple,omitempty"`
	WasInNss              bool                     `protobuf:"varint,17,opt,name=was_in_nss,json=wasInNss" json:"was_in_nss,omitempty"`
	WasInMicrosoft        bool                     `protobuf:"varint,18,opt,name=was_in_microsoft,json=wasInMicrosoft" json:"was_in_microsoft,omitempty"`
	WasInApple            bool                     `protobuf:"varint,19,opt,name=was_in_apple,json=wasInApple" json:"was_in_apple,omitempty"`
	CurrentValidNss       bool                     `protobuf:"varint,20,opt,name=current_valid_nss,json=currentValidNss" json:"current_valid_nss,omitempty"`
	CurrentValidMicrosoft bool                     `protobuf:"varint,21,opt,name=current_valid_microsoft,json=currentValidMicrosoft" json:"current_valid_microsoft,omitempty"`
	CurrentValidApple     bool                     `protobuf:"varint,22,opt,name=current_valid_apple,json=currentValidApple" json:"current_valid_apple,omitempty"`
	CurrentInNss          bool                     `protobuf:"varint,23,opt,name=current_in_nss,json=currentInNss" json:"current_in_nss,omitempty"`
	CurrentInMicrosoft    bool                     `protobuf:"varint,24,opt,name=current_in_microsoft,json=currentInMicrosoft" json:"current_in_microsoft,omitempty"`
	CurrentInApple        bool                     `protobuf:"varint,25,opt,name=current_in_apple,json=currentInApple" json:"current_in_apple,omitempty"`
	NssAudit              *MozillaSalesForceStatus `protobuf:"bytes,31,opt,name=nss_audit,json=nssAudit" json:"nss_audit,omitempty"`
	ShouldPostProcess     bool                     `protobuf:"varint,27,opt,name=should_post_process,json=shouldPostProcess" json:"should_post_process,omitempty"`
	DoNotPostProcess      bool                     `protobuf:"varint,36,opt,name=do_not_post_process,json=doNotPostProcess" json:"do_not_post_process,omitempty"`
}

func (m *Certificate) Reset()                    { *m = Certificate{} }
func (m *Certificate) String() string            { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()               {}
func (*Certificate) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *Certificate) GetSha1Fp() []byte {
	if m != nil {
		return m.Sha1Fp
	}
	return nil
}

func (m *Certificate) GetSha256Fp() []byte {
	if m != nil {
		return m.Sha256Fp
	}
	return nil
}

func (m *Certificate) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

func (m *Certificate) GetParsed() string {
	if m != nil {
		return m.Parsed
	}
	return ""
}

func (m *Certificate) GetParseStatus() CertificateParseStatus {
	if m != nil {
		return m.ParseStatus
	}
	return CertificateParseStatus_CERTIFICATE_PARSE_STATUS_RESERVED
}

func (m *Certificate) GetParseVersion() uint32 {
	if m != nil {
		return m.ParseVersion
	}
	return 0
}

func (m *Certificate) GetParseError() string {
	if m != nil {
		return m.ParseError
	}
	return ""
}

func (m *Certificate) GetParents() [][]byte {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *Certificate) GetPresentedChain() [][]byte {
	if m != nil {
		return m.PresentedChain
	}
	return nil
}

func (m *Certificate) GetSource() CertificateSource {
	if m != nil {
		return m.Source
	}
	return CertificateSource_CERTIFICATE_SOURCE_RESERVED
}

func (m *Certificate) GetSeenInScan() bool {
	if m != nil {
		return m.SeenInScan
	}
	return false
}

func (m *Certificate) GetPostProcessed() bool {
	if m != nil {
		return m.PostProcessed
	}
	return false
}

func (m *Certificate) GetPostProcessTimestamp() uint32 {
	if m != nil {
		return m.PostProcessTimestamp
	}
	return 0
}

func (m *Certificate) GetValidation() *CertificateValidation {
	if m != nil {
		return m.Validation
	}
	return nil
}

func (m *Certificate) GetCt() *CTStatus {
	if m != nil {
		return m.Ct
	}
	return nil
}

func (m *Certificate) GetZlint() *ZLint {
	if m != nil {
		return m.Zlint
	}
	return nil
}

func (m *Certificate) GetRevocation() *CertificateRevocation {
	if m != nil {
		return m.Revocation
	}
	return nil
}

func (m *Certificate) GetAudit() *CertificateAudit {
	if m != nil {
		return m.Audit
	}
	return nil
}

func (m *Certificate) GetIsPrecert() bool {
	if m != nil {
		return m.IsPrecert
	}
	return false
}

func (m *Certificate) GetNotValidAfter() uint32 {
	if m != nil {
		return m.NotValidAfter
	}
	return 0
}

func (m *Certificate) GetNotValidBefore() uint32 {
	if m != nil {
		return m.NotValidBefore
	}
	return 0
}

func (m *Certificate) GetInNss() bool {
	if m != nil {
		return m.InNss
	}
	return false
}

func (m *Certificate) GetInMicrosoft() bool {
	if m != nil {
		return m.InMicrosoft
	}
	return false
}

func (m *Certificate) GetInApple() bool {
	if m != nil {
		return m.InApple
	}
	return false
}

func (m *Certificate) GetValidationTimestamp() uint32 {
	if m != nil {
		return m.ValidationTimestamp
	}
	return 0
}

func (m *Certificate) GetValidNss() bool {
	if m != nil {
		return m.ValidNss
	}
	return false
}

func (m *Certificate) GetValidMicrosoft() bool {
	if m != nil {
		return m.ValidMicrosoft
	}
	return false
}

func (m *Certificate) GetValidApple() bool {
	if m != nil {
		return m.ValidApple
	}
	return false
}

func (m *Certificate) GetWasValidNss() bool {
	if m != nil {
		return m.WasValidNss
	}
	return false
}

func (m *Certificate) GetWasValidMicrosoft() bool {
	if m != nil {
		return m.WasValidMicrosoft
	}
	return false
}

func (m *Certificate) GetWasValidApple() bool {
	if m != nil {
		return m.WasValidApple
	}
	return false
}

func (m *Certificate) GetWasInNss() bool {
	if m != nil {
		return m.WasInNss
	}
	return false
}

func (m *Certificate) GetWasInMicrosoft() bool {
	if m != nil {
		return m.WasInMicrosoft
	}
	return false
}

func (m *Certificate) GetWasInApple() bool {
	if m != nil {
		return m.WasInApple
	}
	return false
}

func (m *Certificate) GetCurrentValidNss() bool {
	if m != nil {
		return m.CurrentValidNss
	}
	return false
}

func (m *Certificate) GetCurrentValidMicrosoft() bool {
	if m != nil {
		return m.CurrentValidMicrosoft
	}
	return false
}

func (m *Certificate) GetCurrentValidApple() bool {
	if m != nil {
		return m.CurrentValidApple
	}
	return false
}

func (m *Certificate) GetCurrentInNss() bool {
	if m != nil {
		return m.CurrentInNss
	}
	return false
}

func (m *Certificate) GetCurrentInMicrosoft() bool {
	if m != nil {
		return m.CurrentInMicrosoft
	}
	return false
}

func (m *Certificate) GetCurrentInApple() bool {
	if m != nil {
		return m.CurrentInApple
	}
	return false
}

func (m *Certificate) GetNssAudit() *MozillaSalesForceStatus {
	if m != nil {
		return m.NssAudit
	}
	return nil
}

func (m *Certificate) GetShouldPostProcess() bool {
	if m != nil {
		return m.ShouldPostProcess
	}
	return false
}

func (m *Certificate) GetDoNotPostProcess() bool {
	if m != nil {
		return m.DoNotPostProcess
	}
	return false
}

func init() {
	proto.RegisterType((*RootStoreStatus)(nil), "censys_definitions.RootStoreStatus")
	proto.RegisterType((*CertificateValidation)(nil), "censys_definitions.CertificateValidation")
	proto.RegisterType((*MozillaSalesForceStatus)(nil), "censys_definitions.MozillaSalesForceStatus")
	proto.RegisterType((*CertificateRevocation)(nil), "censys_definitions.CertificateRevocation")
	proto.RegisterType((*CertificateAudit)(nil), "censys_definitions.CertificateAudit")
	proto.RegisterType((*Certificate)(nil), "censys_definitions.Certificate")
	proto.RegisterEnum("censys_definitions.CertificateType", CertificateType_name, CertificateType_value)
	proto.RegisterEnum("censys_definitions.CertificateSource", CertificateSource_name, CertificateSource_value)
	proto.RegisterEnum("censys_definitions.CertificateParseStatus", CertificateParseStatus_name, CertificateParseStatus_value)
	proto.RegisterEnum("censys_definitions.CertificateRevocationReason", CertificateRevocationReason_name, CertificateRevocationReason_value)
}

func init() { proto.RegisterFile("certificate.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1825 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x58, 0xdd, 0x52, 0xdb, 0x48,
	0x16, 0x5e, 0x7e, 0x0c, 0xf6, 0xb1, 0xb1, 0x45, 0x03, 0x89, 0x80, 0x90, 0x38, 0xfc, 0x24, 0x40,
	0x08, 0x59, 0xd8, 0x64, 0x67, 0x77, 0xaa, 0xe6, 0x42, 0x91, 0xe5, 0xa0, 0x1a, 0xff, 0x55, 0xcb,
	0x90, 0xca, 0xdc, 0xa8, 0x1a, 0xb9, 0x19, 0xb4, 0x63, 0x4b, 0x2a, 0xb5, 0x80, 0x22, 0xef, 0xb1,
	0x2f, 0xb0, 0x37, 0xfb, 0x08, 0xfb, 0x28, 0xfb, 0x10, 0x7b, 0xbb, 0x77, 0x7b, 0xb3, 0xd5, 0xdd,
	0xb2, 0x24, 0x83, 0xc1, 0xcc, 0x15, 0xea, 0x73, 0xbe, 0xef, 0xf4, 0xd7, 0xa7, 0x4f, 0xf7, 0x69,
	0x0c, 0x8b, 0x0e, 0x0d, 0x23, 0xf7, 0xc2, 0x75, 0x48, 0x44, 0x0f, 0x83, 0xd0, 0x8f, 0x7c, 0x84,
	0x1c, 0xea, 0xb1, 0x5b, 0x66, 0xf7, 0xe8, 0x85, 0xeb, 0xb9, 0x91, 0xeb, 0x7b, 0x6c, 0xad, 0xe4,
	0xf8, 0x83, 0x81, 0xef, 0x49, 0xc4, 0x5a, 0xf1, 0x7b, 0xdf, 0xf5, 0xa2, 0x78, 0x90, 0x77, 0xe2,
	0xaf, 0xcd, 0x7f, 0x4c, 0x43, 0x05, 0xfb, 0x7e, 0x64, 0x45, 0x7e, 0x48, 0xad, 0x88, 0x44, 0x57,
	0x0c, 0x2d, 0x43, 0xee, 0x9a, 0xf4, 0xdd, 0x9e, 0x3a, 0x55, 0x9d, 0xda, 0xcd, 0x63, 0x39, 0x40,
	0xeb, 0x50, 0xb8, 0x21, 0xcc, 0x96, 0x9e, 0x69, 0xe1, 0xc9, 0xdf, 0x10, 0x76, 0x26, 0x9c, 0xaf,
	0xa1, 0x14, 0x85, 0x57, 0x2c, 0xa2, 0x3d, 0x3b, 0x20, 0xd1, 0xa5, 0x3a, 0x23, 0xfc, 0xc5, 0xd8,
	0xd6, 0x21, 0xd1, 0x25, 0xda, 0x05, 0x85, 0xf3, 0x47, 0x60, 0xb3, 0x02, 0x56, 0xbe, 0x21, 0xac,
	0x9b, 0x41, 0x56, 0xa1, 0x78, 0xde, 0x27, 0xce, 0x6f, 0x7d, 0x97, 0x9b, 0xd4, 0x9c, 0x8c, 0x95,
	0x31, 0x71, 0xc4, 0xcd, 0xa5, 0x1b, 0xd1, 0x18, 0x31, 0x27, 0x11, 0x19, 0x13, 0xfa, 0x01, 0x66,
	0xa3, 0xdb, 0x80, 0xaa, 0xf3, 0xd5, 0xa9, 0xdd, 0xf2, 0xf1, 0xd6, 0xe1, 0xfd, 0xfc, 0x1c, 0xea,
	0x69, 0x16, 0xbb, 0xb7, 0x01, 0xc5, 0x82, 0x80, 0x10, 0xcc, 0x0a, 0x69, 0xf9, 0xea, 0xcc, 0x6e,
	0x09, 0x8b, 0xef, 0xcd, 0xbf, 0xcf, 0xc0, 0x4a, 0x06, 0x2d, 0x96, 0x4c, 0x78, 0x10, 0xf4, 0x09,
	0x66, 0x3c, 0xc6, 0x44, 0xa2, 0x8a, 0xe3, 0x67, 0xb9, 0x93, 0x5c, 0xcc, 0xf1, 0x48, 0x83, 0xc2,
	0xc0, 0x75, 0x42, 0x9f, 0xf9, 0x17, 0x91, 0xc8, 0xe5, 0x13, 0xc9, 0x29, 0x0b, 0xfd, 0x15, 0x72,
	0x24, 0x08, 0xfa, 0x54, 0xa4, 0xfa, 0x89, 0x74, 0xc9, 0xe0, 0xb9, 0xf9, 0x1b, 0xb9, 0x26, 0x22,
	0xfb, 0x4f, 0x64, 0x0a, 0x02, 0xfa, 0x09, 0xe6, 0x89, 0xd7, 0x0b, 0x7d, 0x57, 0x6e, 0xca, 0x13,
	0xb9, 0x43, 0x0e, 0x6a, 0xc3, 0xe2, 0xaf, 0xbe, 0xff, 0x6b, 0x9f, 0xda, 0x4e, 0x64, 0x07, 0xa1,
	0x3b, 0x20, 0xe1, 0xad, 0x0a, 0x4f, 0x0f, 0x54, 0x91, 0x6c, 0x3d, 0xea, 0x48, 0xee, 0xe6, 0x7f,
	0x66, 0xe0, 0x79, 0xd3, 0xff, 0xee, 0xf6, 0xfb, 0xc4, 0x22, 0x7d, 0xca, 0xea, 0x7e, 0xe8, 0x0c,
	0x8b, 0x78, 0x03, 0xc0, 0xb9, 0x0a, 0x43, 0xea, 0x45, 0xb6, 0xeb, 0xc5, 0x95, 0x5c, 0x88, 0x2d,
	0xa6, 0x87, 0x56, 0x60, 0x8e, 0x57, 0xa3, 0xeb, 0xc5, 0xa5, 0x9c, 0xbb, 0x21, 0xcc, 0xf4, 0x38,
	0xcb, 0xbf, 0xf1, 0x68, 0x68, 0x7b, 0x64, 0x20, 0x53, 0x5b, 0xc0, 0x05, 0x61, 0x69, 0x91, 0x01,
	0x45, 0xaf, 0xa0, 0x18, 0x10, 0x11, 0x53, 0xf8, 0x67, 0x85, 0x1f, 0xa4, 0x49, 0x00, 0xf6, 0x40,
	0xc9, 0x1c, 0x4e, 0x89, 0xca, 0x09, 0x54, 0x25, 0x63, 0x17, 0xd0, 0xf7, 0x80, 0xb2, 0xd0, 0xc0,
	0xef, 0xbb, 0xce, 0xad, 0x28, 0xe5, 0x02, 0xce, 0x9e, 0xf0, 0x8e, 0x70, 0xa0, 0x13, 0xa8, 0xa6,
	0x46, 0xd7, 0xf7, 0xec, 0x20, 0x24, 0x4e, 0xe4, 0x3a, 0xd4, 0x66, 0x11, 0x89, 0xe8, 0x80, 0x7a,
	0x91, 0x28, 0xf6, 0x02, 0x7e, 0x39, 0x82, 0xeb, 0xc4, 0x30, 0x6b, 0x88, 0x42, 0x7b, 0xb0, 0xe8,
	0x04, 0x36, 0x23, 0x03, 0x6a, 0x13, 0x66, 0x4b, 0xf1, 0x6a, 0x5e, 0x9e, 0x44, 0x27, 0xb0, 0xc8,
	0x80, 0x6a, 0xac, 0x23, 0xac, 0xe8, 0x03, 0x2c, 0x93, 0xab, 0x9e, 0x1b, 0xdd, 0x45, 0x17, 0x04,
	0x7a, 0x51, 0xf8, 0x46, 0x08, 0x3b, 0x50, 0x66, 0x11, 0xf1, 0x7a, 0x24, 0xec, 0xd9, 0xc2, 0x2b,
	0xf6, 0xb7, 0x80, 0x17, 0x86, 0x56, 0x8d, 0x1b, 0xd1, 0x2a, 0xe4, 0xcf, 0xc3, 0x18, 0x50, 0x14,
	0x80, 0xf9, 0xf3, 0x50, 0xba, 0x54, 0x98, 0x17, 0x76, 0x3f, 0x54, 0x4b, 0xd2, 0x13, 0x0f, 0x37,
	0xbf, 0x8f, 0x1c, 0x42, 0x4c, 0xaf, 0x7d, 0xb9, 0x42, 0x4e, 0x09, 0xe9, 0xb5, 0xff, 0x1b, 0x1d,
	0xde, 0x58, 0xc3, 0x21, 0xfa, 0x02, 0x73, 0x21, 0x25, 0xcc, 0x97, 0xbb, 0x5c, 0x3e, 0xfe, 0x30,
	0xe1, 0x1e, 0x48, 0x83, 0x62, 0x41, 0xc3, 0x31, 0x7d, 0xf3, 0x1b, 0x28, 0x19, 0x98, 0x54, 0x6a,
	0xc0, 0xfc, 0x40, 0x16, 0x5f, 0x7c, 0xfe, 0xdf, 0x8d, 0x8b, 0xfe, 0x40, 0x7d, 0xe2, 0x21, 0x77,
	0xf3, 0x7f, 0x65, 0x28, 0x66, 0x62, 0xa3, 0x67, 0x30, 0xc7, 0x2e, 0xc9, 0xd1, 0x45, 0x20, 0xa2,
	0x96, 0x70, 0x3c, 0x42, 0x6b, 0x90, 0x67, 0x97, 0xe4, 0xf8, 0xd3, 0x9f, 0x2f, 0x02, 0xb1, 0x9a,
	0x12, 0x4e, 0xc6, 0x48, 0x81, 0x99, 0x90, 0xdc, 0x88, 0x7a, 0x2d, 0x61, 0xfe, 0xc9, 0xa3, 0x04,
	0x24, 0x64, 0xb4, 0x17, 0x17, 0x69, 0x3c, 0x42, 0x4d, 0x28, 0x89, 0x2f, 0x51, 0x35, 0x57, 0x4c,
	0x3d, 0x10, 0x79, 0xd9, 0x9f, 0x90, 0x97, 0x0e, 0xa7, 0xc4, 0xc2, 0x8b, 0x41, 0x3a, 0x40, 0x5b,
	0xb0, 0x20, 0xc3, 0x5d, 0xd3, 0x90, 0xb9, 0xbe, 0xa7, 0xbe, 0xad, 0x4e, 0xed, 0x2e, 0x60, 0x39,
	0xc7, 0x99, 0xb4, 0xc5, 0xa7, 0x86, 0x51, 0x9b, 0x86, 0xa1, 0x1f, 0xaa, 0x1f, 0x92, 0x53, 0xc3,
	0xa8, 0xc1, 0x2d, 0x7c, 0x03, 0x65, 0x61, 0x31, 0x35, 0x27, 0xae, 0xdd, 0xe1, 0x10, 0xbd, 0x85,
	0x4a, 0x10, 0x52, 0x46, 0x3d, 0xde, 0x32, 0x9c, 0x4b, 0xe2, 0x7a, 0xea, 0x7b, 0x81, 0x28, 0x27,
	0x66, 0x9d, 0x5b, 0xd1, 0x4f, 0x30, 0xc7, 0xfc, 0xab, 0xd0, 0xa1, 0xea, 0x0b, 0xb1, 0xa2, 0x9d,
	0x09, 0x2b, 0xb2, 0x04, 0x18, 0xc7, 0x24, 0x54, 0x85, 0x12, 0xa3, 0xd4, 0xb3, 0x5d, 0xcf, 0x66,
	0x0e, 0xf1, 0xd4, 0x0d, 0x51, 0x47, 0xc0, 0x6d, 0xa6, 0x67, 0x39, 0xc4, 0xe3, 0x95, 0x1d, 0xf8,
	0x8c, 0xdf, 0x5b, 0xbe, 0x43, 0x19, 0x4f, 0xec, 0x9a, 0xc0, 0x2c, 0x70, 0x6b, 0x67, 0x68, 0x44,
	0x1f, 0xe1, 0x59, 0x16, 0x66, 0x47, 0xee, 0x80, 0xb2, 0x88, 0x0c, 0x02, 0x75, 0x47, 0x64, 0x66,
	0x39, 0x03, 0xef, 0x0e, 0x7d, 0xc8, 0x04, 0xb8, 0x4e, 0x9a, 0x8a, 0xba, 0x25, 0xaa, 0x69, 0x6f,
	0xc2, 0x0a, 0xd2, 0x2e, 0x84, 0x33, 0x64, 0x74, 0x00, 0xd3, 0x4e, 0xa4, 0xbe, 0x14, 0x21, 0x5e,
	0x8c, 0x0d, 0xd1, 0x8d, 0x37, 0x72, 0xda, 0xe1, 0x07, 0x3c, 0x27, 0xde, 0x05, 0xea, 0x1b, 0x41,
	0x58, 0x1d, 0x47, 0xf8, 0xa5, 0xe1, 0x7a, 0x11, 0x96, 0x38, 0xae, 0x34, 0x4c, 0x0e, 0x89, 0xfa,
	0xee, 0x49, 0x4a, 0x33, 0xa7, 0x2a, 0x43, 0x46, 0x3f, 0x42, 0x4e, 0xde, 0x00, 0x87, 0x22, 0xca,
	0xf6, 0x84, 0x28, 0xe2, 0xd0, 0x61, 0x49, 0xe1, 0xf7, 0xb4, 0xcb, 0xec, 0x20, 0xa4, 0xfc, 0xae,
	0x53, 0xab, 0xf2, 0x76, 0x77, 0x59, 0x47, 0x1a, 0xd0, 0x1b, 0xa8, 0x78, 0x7e, 0x24, 0xdf, 0x2a,
	0x36, 0xb9, 0x88, 0x68, 0xa8, 0xee, 0x89, 0xf4, 0x2f, 0x78, 0x7e, 0x24, 0x12, 0xa7, 0x71, 0x23,
	0x7f, 0x93, 0xa4, 0xb8, 0x73, 0x7a, 0xe1, 0x87, 0x54, 0xdd, 0x17, 0xc0, 0xf2, 0x10, 0xf8, 0x59,
	0x58, 0x79, 0xbf, 0x70, 0x3d, 0x9b, 0xf7, 0x7a, 0xf9, 0xd8, 0xc8, 0xb9, 0x5e, 0x8b, 0x31, 0xb4,
	0x03, 0x25, 0xd7, 0xb3, 0xd3, 0x5e, 0xce, 0x6f, 0xe0, 0xfc, 0xe7, 0x69, 0x75, 0x0a, 0x17, 0x5d,
	0xaf, 0x99, 0x34, 0xeb, 0x0d, 0xc8, 0xbb, 0x9e, 0x2d, 0xfb, 0x75, 0x3e, 0x81, 0xcc, 0xbb, 0x9e,
	0x26, 0x1a, 0xf2, 0x11, 0x2c, 0xa7, 0x3b, 0x98, 0x29, 0x19, 0x10, 0x52, 0x96, 0x52, 0x5f, 0x5a,
	0x31, 0xaf, 0xa0, 0x20, 0x55, 0x73, 0x49, 0xc5, 0x24, 0x64, 0x5e, 0x18, 0xb9, 0xb2, 0x77, 0x50,
	0x91, 0x80, 0x54, 0x5c, 0x29, 0x81, 0x95, 0x85, 0x2b, 0xd5, 0xb7, 0x05, 0xc5, 0x38, 0x57, 0x42,
	0xe2, 0x42, 0x02, 0x94, 0x95, 0x25, 0x55, 0x6e, 0xc2, 0x42, 0xf2, 0x00, 0x14, 0xd3, 0x96, 0xe3,
	0x67, 0x57, 0xfc, 0x08, 0xe4, 0xb3, 0x1e, 0xc3, 0x52, 0x8a, 0x49, 0x67, 0xae, 0x24, 0x01, 0x17,
	0x87, 0xe8, 0x74, 0xf2, 0x7d, 0xa8, 0xa4, 0x1c, 0x29, 0x40, 0x49, 0xf0, 0x0b, 0x43, 0xbc, 0xd4,
	0x50, 0x05, 0x90, 0x6d, 0x5b, 0x08, 0x58, 0x4c, 0xd7, 0x2d, 0xda, 0x37, 0x57, 0x70, 0x20, 0x9f,
	0x99, 0x23, 0xbb, 0x82, 0xd2, 0x85, 0x0b, 0x5c, 0x3a, 0xf7, 0x36, 0x94, 0x62, 0xb4, 0x9c, 0x78,
	0x29, 0x5d, 0xb9, 0x40, 0xca, 0x59, 0xf7, 0x61, 0x71, 0xf8, 0x96, 0x48, 0x57, 0xbf, 0x2c, 0x56,
	0x5f, 0x89, 0x1d, 0x49, 0x06, 0x7e, 0x84, 0xe7, 0xa3, 0xd8, 0x54, 0xc6, 0x4a, 0x12, 0x7c, 0x25,
	0xcb, 0x4a, 0xd5, 0x1c, 0xc3, 0xd2, 0x28, 0x57, 0x8a, 0x7a, 0x96, 0x66, 0x2f, 0xcb, 0x93, 0xda,
	0xb6, 0xa1, 0x9c, 0xbe, 0x73, 0x84, 0xb0, 0xe7, 0x42, 0x58, 0x29, 0x79, 0xeb, 0x70, 0x55, 0x1f,
	0x61, 0x39, 0x83, 0x4a, 0x25, 0xa9, 0x49, 0x68, 0x94, 0xe0, 0x53, 0x3d, 0x07, 0xa0, 0x64, 0x58,
	0x52, 0xcc, 0x6a, 0x9a, 0xcb, 0x84, 0x21, 0x95, 0x34, 0xa0, 0xe0, 0x31, 0x16, 0x77, 0xf5, 0x57,
	0xbf, 0xbb, 0x23, 0xca, 0x7d, 0xf4, 0x18, 0x93, 0xdd, 0xf5, 0x18, 0x96, 0xd8, 0xa5, 0x7f, 0xd5,
	0xef, 0xd9, 0xd9, 0xfb, 0x54, 0x5d, 0x4f, 0x73, 0x21, 0xdd, 0x9d, 0xf4, 0x3e, 0x45, 0x47, 0xb0,
	0xd4, 0xf3, 0x6d, 0x7e, 0xa2, 0x47, 0x38, 0xdb, 0x09, 0x47, 0xe9, 0xf9, 0x2d, 0x3f, 0xca, 0x50,
	0xf6, 0xff, 0x39, 0x05, 0x95, 0x3b, 0xff, 0x08, 0xa0, 0x0d, 0x58, 0xd5, 0x0d, 0xdc, 0x35, 0xeb,
	0xa6, 0xae, 0x75, 0x0d, 0xbb, 0xfb, 0xad, 0x63, 0xd8, 0xd8, 0xb0, 0x0c, 0x7c, 0x66, 0xd4, 0x94,
	0x3f, 0xa0, 0x17, 0xa0, 0xde, 0x73, 0x9f, 0xb6, 0x7e, 0x6e, 0xb5, 0xbf, 0xb6, 0x94, 0x29, 0xb4,
	0x0a, 0x2b, 0xf7, 0xbc, 0x0d, 0x43, 0xab, 0x2b, 0xd3, 0xe8, 0x35, 0x6c, 0xdc, 0x73, 0x99, 0xad,
	0xae, 0x81, 0x9b, 0x46, 0xcd, 0xd4, 0xba, 0x86, 0x32, 0x33, 0x96, 0x8d, 0xdb, 0xed, 0xae, 0x32,
	0xbb, 0xff, 0xaf, 0x69, 0x58, 0xbc, 0xd7, 0xc0, 0xd0, 0x2b, 0x58, 0xcf, 0x12, 0xac, 0xf6, 0x29,
	0xd6, 0x47, 0xd4, 0xbe, 0x84, 0xb5, 0x31, 0x80, 0x54, 0xef, 0x3a, 0x3c, 0x1f, 0xe3, 0xb7, 0x74,
	0xad, 0xa5, 0x4c, 0xdf, 0x95, 0x13, 0x3b, 0xf5, 0xae, 0x32, 0x83, 0xf6, 0x60, 0x67, 0x8c, 0xab,
	0xd9, 0xfe, 0xc5, 0x6c, 0x34, 0x34, 0xdb, 0xd2, 0x1a, 0x86, 0x55, 0x6f, 0x63, 0xdd, 0x50, 0x66,
	0x1f, 0xd1, 0xa8, 0x61, 0xfd, 0x44, 0xc9, 0xdd, 0x4d, 0xf8, 0x10, 0xa0, 0x75, 0xcc, 0xda, 0x0f,
	0xca, 0xdc, 0x03, 0xee, 0x93, 0xd3, 0xcf, 0x9f, 0x1b, 0x86, 0x32, 0xff, 0x40, 0x78, 0xbd, 0x6b,
	0xeb, 0x27, 0x9a, 0xd9, 0x52, 0xf2, 0xfb, 0xff, 0x9e, 0x82, 0x67, 0xe3, 0x1f, 0x33, 0x68, 0x07,
	0x5e, 0x67, 0xb9, 0x1d, 0x0d, 0x5b, 0x86, 0x6d, 0x75, 0xb5, 0xee, 0xa9, 0x95, 0x4d, 0xe2, 0x36,
	0x54, 0x1f, 0x84, 0xa5, 0xa9, 0x7c, 0x0c, 0x65, 0x9d, 0xea, 0xba, 0x61, 0x59, 0xf7, 0xab, 0x60,
	0x04, 0x55, 0xd7, 0xcc, 0x86, 0x32, 0x83, 0xde, 0xc2, 0xd6, 0x83, 0x90, 0x56, 0xbb, 0x2b, 0x0d,
	0x35, 0x65, 0x76, 0xff, 0xbf, 0xb3, 0xb0, 0xfe, 0xc8, 0xf3, 0x15, 0xed, 0xc3, 0x9b, 0x6c, 0x20,
	0x6c, 0x9c, 0xb5, 0x75, 0xad, 0x6b, 0xb6, 0x5b, 0x36, 0x36, 0x34, 0x4b, 0xfc, 0x49, 0xd6, 0x78,
	0x67, 0x43, 0xef, 0x63, 0xd3, 0x85, 0xbe, 0x87, 0xbd, 0x49, 0x50, 0xab, 0x63, 0xe8, 0x66, 0xdd,
	0x34, 0x6a, 0xca, 0x34, 0xfa, 0x23, 0x1c, 0x3c, 0x0e, 0xff, 0xd9, 0xf8, 0x66, 0xeb, 0xed, 0x66,
	0x07, 0xb7, 0x9b, 0xa6, 0xc5, 0x8f, 0xc1, 0x07, 0x78, 0xf7, 0x38, 0x43, 0xd7, 0xb2, 0x84, 0x59,
	0xf4, 0x09, 0x8e, 0x1e, 0x27, 0x68, 0xf5, 0xba, 0xd9, 0x30, 0xa5, 0x49, 0x3f, 0xd1, 0x5a, 0x5f,
	0x8c, 0x9a, 0x92, 0x43, 0x07, 0xb0, 0xfb, 0x38, 0xcd, 0x3a, 0xed, 0x18, 0x3c, 0xd7, 0x46, 0x4d,
	0x99, 0x43, 0x7f, 0x81, 0x8f, 0x13, 0x54, 0x19, 0x96, 0x25, 0x0d, 0xed, 0xba, 0xdd, 0xee, 0x18,
	0x58, 0x0c, 0x94, 0x79, 0x74, 0x0c, 0x87, 0x93, 0x98, 0xa9, 0xf7, 0xa4, 0xdd, 0xa8, 0x29, 0x79,
	0x74, 0x04, 0xef, 0x27, 0xed, 0x5d, 0xb3, 0x7d, 0x66, 0xd8, 0x75, 0xdc, 0x6e, 0xda, 0x3a, 0x6e,
	0x28, 0x85, 0xc9, 0x59, 0xe8, 0x60, 0xf3, 0xcc, 0x6c, 0x18, 0x5f, 0x0c, 0xfb, 0xab, 0xd9, 0x3d,
	0xa9, 0x61, 0xed, 0x6b, 0x4b, 0x81, 0xc9, 0xd9, 0xd6, 0x46, 0xb2, 0x5d, 0x3c, 0x9f, 0x13, 0xbf,
	0x1d, 0xfd, 0xe9, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xfb, 0x07, 0x5e, 0x89, 0x12, 0x00,
	0x00,
}
