// Code generated by protoc-gen-go.
// source: certificate.proto
// DO NOT EDIT!

package censys_definitions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CertificateType int32

const (
	CertificateType_CERTIFICATE_TYPE_RESERVED     CertificateType = 0
	CertificateType_CERTIFICATE_TYPE_UNKNOWN      CertificateType = 1
	CertificateType_CERTIFICATE_TYPE_LEAF         CertificateType = 2
	CertificateType_CERTIFICATE_TYPE_INTERMEDIATE CertificateType = 3
	CertificateType_CERTIFICATE_TYPE_ROOT         CertificateType = 4
)

var CertificateType_name = map[int32]string{
	0: "CERTIFICATE_TYPE_RESERVED",
	1: "CERTIFICATE_TYPE_UNKNOWN",
	2: "CERTIFICATE_TYPE_LEAF",
	3: "CERTIFICATE_TYPE_INTERMEDIATE",
	4: "CERTIFICATE_TYPE_ROOT",
}
var CertificateType_value = map[string]int32{
	"CERTIFICATE_TYPE_RESERVED":     0,
	"CERTIFICATE_TYPE_UNKNOWN":      1,
	"CERTIFICATE_TYPE_LEAF":         2,
	"CERTIFICATE_TYPE_INTERMEDIATE": 3,
	"CERTIFICATE_TYPE_ROOT":         4,
}

func (x CertificateType) String() string {
	return proto.EnumName(CertificateType_name, int32(x))
}
func (CertificateType) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

type CertificateSource int32

const (
	CertificateSource_CERTIFICATE_SOURCE_RESERVED           CertificateSource = 0
	CertificateSource_CERTIFICATE_SOURCE_UNKNOWN            CertificateSource = 1
	CertificateSource_CERTIFICATE_SOURCE_SCAN               CertificateSource = 2
	CertificateSource_CERTIFICATE_SOURCE_CT                 CertificateSource = 3
	CertificateSource_CERTIFICATE_SOURCE_MOZILLA_SALESFORCE CertificateSource = 4
	CertificateSource_CERTIFICATE_SOURCE_RESEARCH           CertificateSource = 5
	CertificateSource_CERTIFICATE_SOURCE_RAPID7             CertificateSource = 6
	CertificateSource_CERTIFICATE_SOURCE_HUBBLE             CertificateSource = 7
	CertificateSource_CERTIFICATE_SOURCE_CT_CHAIN           CertificateSource = 8
)

var CertificateSource_name = map[int32]string{
	0: "CERTIFICATE_SOURCE_RESERVED",
	1: "CERTIFICATE_SOURCE_UNKNOWN",
	2: "CERTIFICATE_SOURCE_SCAN",
	3: "CERTIFICATE_SOURCE_CT",
	4: "CERTIFICATE_SOURCE_MOZILLA_SALESFORCE",
	5: "CERTIFICATE_SOURCE_RESEARCH",
	6: "CERTIFICATE_SOURCE_RAPID7",
	7: "CERTIFICATE_SOURCE_HUBBLE",
	8: "CERTIFICATE_SOURCE_CT_CHAIN",
}
var CertificateSource_value = map[string]int32{
	"CERTIFICATE_SOURCE_RESERVED":           0,
	"CERTIFICATE_SOURCE_UNKNOWN":            1,
	"CERTIFICATE_SOURCE_SCAN":               2,
	"CERTIFICATE_SOURCE_CT":                 3,
	"CERTIFICATE_SOURCE_MOZILLA_SALESFORCE": 4,
	"CERTIFICATE_SOURCE_RESEARCH":           5,
	"CERTIFICATE_SOURCE_RAPID7":             6,
	"CERTIFICATE_SOURCE_HUBBLE":             7,
	"CERTIFICATE_SOURCE_CT_CHAIN":           8,
}

func (x CertificateSource) String() string {
	return proto.EnumName(CertificateSource_name, int32(x))
}
func (CertificateSource) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

type CertificateParseStatus int32

const (
	CertificateParseStatus_CERTIFICATE_PARSE_STATUS_RESERVED   CertificateParseStatus = 0
	CertificateParseStatus_CERTIFICATE_PARSE_STATUS_UNKNOWN    CertificateParseStatus = 1
	CertificateParseStatus_CERTIFICATE_PARSE_STATUS_SUCCESS    CertificateParseStatus = 2
	CertificateParseStatus_CERTIFICATE_PARSE_STATUS_FAIL       CertificateParseStatus = 3
	CertificateParseStatus_CERTIFICATE_PARSE_STATUS_NOT_PARSED CertificateParseStatus = 4
)

var CertificateParseStatus_name = map[int32]string{
	0: "CERTIFICATE_PARSE_STATUS_RESERVED",
	1: "CERTIFICATE_PARSE_STATUS_UNKNOWN",
	2: "CERTIFICATE_PARSE_STATUS_SUCCESS",
	3: "CERTIFICATE_PARSE_STATUS_FAIL",
	4: "CERTIFICATE_PARSE_STATUS_NOT_PARSED",
}
var CertificateParseStatus_value = map[string]int32{
	"CERTIFICATE_PARSE_STATUS_RESERVED":   0,
	"CERTIFICATE_PARSE_STATUS_UNKNOWN":    1,
	"CERTIFICATE_PARSE_STATUS_SUCCESS":    2,
	"CERTIFICATE_PARSE_STATUS_FAIL":       3,
	"CERTIFICATE_PARSE_STATUS_NOT_PARSED": 4,
}

func (x CertificateParseStatus) String() string {
	return proto.EnumName(CertificateParseStatus_name, int32(x))
}
func (CertificateParseStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

type CertificateRevocationReason int32

const (
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_RESERVED CertificateRevocationReason = 0
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_UNKNOWN  CertificateRevocationReason = 1
	// RFC 5280
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_UNSPECIFIED            CertificateRevocationReason = 2
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_KEY_COMPROMISE         CertificateRevocationReason = 3
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_CA_COMPROMISE          CertificateRevocationReason = 4
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_AFFILIATION_CHANGED    CertificateRevocationReason = 5
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_SUPERSEDED             CertificateRevocationReason = 6
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_CESSATION_OF_OPERATION CertificateRevocationReason = 7
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_CERTIFICATE_HOLD       CertificateRevocationReason = 8
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_REMOVE_FROM_CRL        CertificateRevocationReason = 9
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_PRIVILEGE_WITHDRAWN    CertificateRevocationReason = 10
	CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_AA_COMPROMISE          CertificateRevocationReason = 11
)

var CertificateRevocationReason_name = map[int32]string{
	0:  "CERTIFICATE_REVOCATION_REASON_RESERVED",
	1:  "CERTIFICATE_REVOCATION_REASON_UNKNOWN",
	2:  "CERTIFICATE_REVOCATION_REASON_UNSPECIFIED",
	3:  "CERTIFICATE_REVOCATION_REASON_KEY_COMPROMISE",
	4:  "CERTIFICATE_REVOCATION_REASON_CA_COMPROMISE",
	5:  "CERTIFICATE_REVOCATION_REASON_AFFILIATION_CHANGED",
	6:  "CERTIFICATE_REVOCATION_REASON_SUPERSEDED",
	7:  "CERTIFICATE_REVOCATION_REASON_CESSATION_OF_OPERATION",
	8:  "CERTIFICATE_REVOCATION_REASON_CERTIFICATE_HOLD",
	9:  "CERTIFICATE_REVOCATION_REASON_REMOVE_FROM_CRL",
	10: "CERTIFICATE_REVOCATION_REASON_PRIVILEGE_WITHDRAWN",
	11: "CERTIFICATE_REVOCATION_REASON_AA_COMPROMISE",
}
var CertificateRevocationReason_value = map[string]int32{
	"CERTIFICATE_REVOCATION_REASON_RESERVED":               0,
	"CERTIFICATE_REVOCATION_REASON_UNKNOWN":                1,
	"CERTIFICATE_REVOCATION_REASON_UNSPECIFIED":            2,
	"CERTIFICATE_REVOCATION_REASON_KEY_COMPROMISE":         3,
	"CERTIFICATE_REVOCATION_REASON_CA_COMPROMISE":          4,
	"CERTIFICATE_REVOCATION_REASON_AFFILIATION_CHANGED":    5,
	"CERTIFICATE_REVOCATION_REASON_SUPERSEDED":             6,
	"CERTIFICATE_REVOCATION_REASON_CESSATION_OF_OPERATION": 7,
	"CERTIFICATE_REVOCATION_REASON_CERTIFICATE_HOLD":       8,
	"CERTIFICATE_REVOCATION_REASON_REMOVE_FROM_CRL":        9,
	"CERTIFICATE_REVOCATION_REASON_PRIVILEGE_WITHDRAWN":    10,
	"CERTIFICATE_REVOCATION_REASON_AA_COMPROMISE":          11,
}

func (x CertificateRevocationReason) String() string {
	return proto.EnumName(CertificateRevocationReason_name, int32(x))
}
func (CertificateRevocationReason) EnumDescriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

type Path struct {
	// Contains SHA256 fingerprints of a chain of certificates
	Sha256Fp [][]byte `protobuf:"bytes,1,rep,name=sha256fp,proto3" json:"sha256fp,omitempty"`
}

func (m *Path) Reset()                    { *m = Path{} }
func (m *Path) String() string            { return proto.CompactTextString(m) }
func (*Path) ProtoMessage()               {}
func (*Path) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{0} }

func (m *Path) GetSha256Fp() [][]byte {
	if m != nil {
		return m.Sha256Fp
	}
	return nil
}

type RootStoreStatus struct {
	// ((has_trusted_path && !revoked && !blacklisted) || whitelisted) && !expired
	Valid bool `protobuf:"varint,1,opt,name=valid" json:"valid,omitempty"`
	// True if the certificate is valid now or was ever valid in the past.
	WasValid bool `protobuf:"varint,2,opt,name=was_valid,json=wasValid" json:"was_valid,omitempty"`
	// True if there exists a path from the certificate to the root store.
	HasTrustedPath bool `protobuf:"varint,3,opt,name=has_trusted_path,json=hasTrustedPath" json:"has_trusted_path,omitempty"`
	// True if now or at some point in the past there existed a path from the
	// certificate to the root store.
	HadTrustedPath bool `protobuf:"varint,4,opt,name=had_trusted_path,json=hadTrustedPath" json:"had_trusted_path,omitempty"`
	// True if the certificate is explicitly blacklisted by some method other
	// than OneCRL / CRLSet. For example, a set of certificates revoked by
	// Cloudflare are blacklisted by SPKI hash in Chrome.
	Blacklisted bool `protobuf:"varint,5,opt,name=blacklisted" json:"blacklisted,omitempty"`
	// True if the certificate is explicitly whitelisted, e.g. the set of
	// trusted WoSign certificates Apple uses.
	Whitelisted bool `protobuf:"varint,6,opt,name=whitelisted" json:"whitelisted,omitempty"`
	// Indicates if the certificate is a root, intermediate, or leaf.
	Type CertificateType `protobuf:"varint,7,opt,name=type,enum=zsearch.CertificateType" json:"type,omitempty"`
	// Current trusted paths to the root store. Only valid if
	// `has_trusted_paths = true`.
	TrustedPaths []*Path `protobuf:"bytes,8,rep,name=trusted_paths,json=trustedPaths" json:"trusted_paths,omitempty"`
	// True if the certificate is in the revocation set (e.g. OneCRL)
	// associated with this root store.
	InRevocationSet bool `protobuf:"varint,9,opt,name=in_revocation_set,json=inRevocationSet" json:"in_revocation_set,omitempty"`
	// SHA256 fingerprints of immediate parents.
	Parents [][]byte `protobuf:"bytes,10,rep,name=parents,proto3" json:"parents,omitempty"`
}

func (m *RootStoreStatus) Reset()                    { *m = RootStoreStatus{} }
func (m *RootStoreStatus) String() string            { return proto.CompactTextString(m) }
func (*RootStoreStatus) ProtoMessage()               {}
func (*RootStoreStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{1} }

func (m *RootStoreStatus) GetValid() bool {
	if m != nil {
		return m.Valid
	}
	return false
}

func (m *RootStoreStatus) GetWasValid() bool {
	if m != nil {
		return m.WasValid
	}
	return false
}

func (m *RootStoreStatus) GetHasTrustedPath() bool {
	if m != nil {
		return m.HasTrustedPath
	}
	return false
}

func (m *RootStoreStatus) GetHadTrustedPath() bool {
	if m != nil {
		return m.HadTrustedPath
	}
	return false
}

func (m *RootStoreStatus) GetBlacklisted() bool {
	if m != nil {
		return m.Blacklisted
	}
	return false
}

func (m *RootStoreStatus) GetWhitelisted() bool {
	if m != nil {
		return m.Whitelisted
	}
	return false
}

func (m *RootStoreStatus) GetType() CertificateType {
	if m != nil {
		return m.Type
	}
	return CertificateType_CERTIFICATE_TYPE_RESERVED
}

func (m *RootStoreStatus) GetTrustedPaths() []*Path {
	if m != nil {
		return m.TrustedPaths
	}
	return nil
}

func (m *RootStoreStatus) GetInRevocationSet() bool {
	if m != nil {
		return m.InRevocationSet
	}
	return false
}

func (m *RootStoreStatus) GetParents() [][]byte {
	if m != nil {
		return m.Parents
	}
	return nil
}

type CertificateValidation struct {
	Nss       *RootStoreStatus `protobuf:"bytes,1,opt,name=nss" json:"nss,omitempty"`
	Microsoft *RootStoreStatus `protobuf:"bytes,2,opt,name=microsoft" json:"microsoft,omitempty"`
	Apple     *RootStoreStatus `protobuf:"bytes,3,opt,name=apple" json:"apple,omitempty"`
	Java      *RootStoreStatus `protobuf:"bytes,4,opt,name=java" json:"java,omitempty"`
	Android   *RootStoreStatus `protobuf:"bytes,5,opt,name=android" json:"android,omitempty"`
	// also track for Google CT servers so we know what to push
	GoogleCtPrimary *RootStoreStatus `protobuf:"bytes,10,opt,name=google_ct_primary,json=googleCtPrimary" json:"google_ct_primary,omitempty"`
}

func (m *CertificateValidation) Reset()                    { *m = CertificateValidation{} }
func (m *CertificateValidation) String() string            { return proto.CompactTextString(m) }
func (*CertificateValidation) ProtoMessage()               {}
func (*CertificateValidation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{2} }

func (m *CertificateValidation) GetNss() *RootStoreStatus {
	if m != nil {
		return m.Nss
	}
	return nil
}

func (m *CertificateValidation) GetMicrosoft() *RootStoreStatus {
	if m != nil {
		return m.Microsoft
	}
	return nil
}

func (m *CertificateValidation) GetApple() *RootStoreStatus {
	if m != nil {
		return m.Apple
	}
	return nil
}

func (m *CertificateValidation) GetJava() *RootStoreStatus {
	if m != nil {
		return m.Java
	}
	return nil
}

func (m *CertificateValidation) GetAndroid() *RootStoreStatus {
	if m != nil {
		return m.Android
	}
	return nil
}

func (m *CertificateValidation) GetGoogleCtPrimary() *RootStoreStatus {
	if m != nil {
		return m.GoogleCtPrimary
	}
	return nil
}

type MozillaSalesForceStatus struct {
	CurrentIn                      bool   `protobuf:"varint,1,opt,name=current_in,json=currentIn" json:"current_in,omitempty"`
	WasIn                          bool   `protobuf:"varint,2,opt,name=was_in,json=wasIn" json:"was_in,omitempty"`
	OwnerName                      string `protobuf:"bytes,3,opt,name=owner_name,json=ownerName" json:"owner_name,omitempty"`
	ParentName                     string `protobuf:"bytes,4,opt,name=parent_name,json=parentName" json:"parent_name,omitempty"`
	CertificateName                string `protobuf:"bytes,5,opt,name=certificate_name,json=certificateName" json:"certificate_name,omitempty"`
	CertificatePolicy              string `protobuf:"bytes,6,opt,name=certificate_policy,json=certificatePolicy" json:"certificate_policy,omitempty"`
	CertificationPracticeStatement string `protobuf:"bytes,7,opt,name=certification_practice_statement,json=certificationPracticeStatement" json:"certification_practice_statement,omitempty"`
	CpSameAsParent                 bool   `protobuf:"varint,8,opt,name=cp_same_as_parent,json=cpSameAsParent" json:"cp_same_as_parent,omitempty"`
	AuditSameAsParent              bool   `protobuf:"varint,9,opt,name=audit_same_as_parent,json=auditSameAsParent" json:"audit_same_as_parent,omitempty"`
	StandardAudit                  string `protobuf:"bytes,10,opt,name=standard_audit,json=standardAudit" json:"standard_audit,omitempty"`
	BrAudit                        string `protobuf:"bytes,11,opt,name=br_audit,json=brAudit" json:"br_audit,omitempty"`
	Auditor                        string `protobuf:"bytes,12,opt,name=auditor" json:"auditor,omitempty"`
}

func (m *MozillaSalesForceStatus) Reset()                    { *m = MozillaSalesForceStatus{} }
func (m *MozillaSalesForceStatus) String() string            { return proto.CompactTextString(m) }
func (*MozillaSalesForceStatus) ProtoMessage()               {}
func (*MozillaSalesForceStatus) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{3} }

func (m *MozillaSalesForceStatus) GetCurrentIn() bool {
	if m != nil {
		return m.CurrentIn
	}
	return false
}

func (m *MozillaSalesForceStatus) GetWasIn() bool {
	if m != nil {
		return m.WasIn
	}
	return false
}

func (m *MozillaSalesForceStatus) GetOwnerName() string {
	if m != nil {
		return m.OwnerName
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetParentName() string {
	if m != nil {
		return m.ParentName
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetCertificateName() string {
	if m != nil {
		return m.CertificateName
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetCertificatePolicy() string {
	if m != nil {
		return m.CertificatePolicy
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetCertificationPracticeStatement() string {
	if m != nil {
		return m.CertificationPracticeStatement
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetCpSameAsParent() bool {
	if m != nil {
		return m.CpSameAsParent
	}
	return false
}

func (m *MozillaSalesForceStatus) GetAuditSameAsParent() bool {
	if m != nil {
		return m.AuditSameAsParent
	}
	return false
}

func (m *MozillaSalesForceStatus) GetStandardAudit() string {
	if m != nil {
		return m.StandardAudit
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetBrAudit() string {
	if m != nil {
		return m.BrAudit
	}
	return ""
}

func (m *MozillaSalesForceStatus) GetAuditor() string {
	if m != nil {
		return m.Auditor
	}
	return ""
}

type CertificateRevocation struct {
	Revoked bool                        `protobuf:"varint,1,opt,name=revoked" json:"revoked,omitempty"`
	Reason  CertificateRevocationReason `protobuf:"varint,2,opt,name=reason,enum=zsearch.CertificateRevocationReason" json:"reason,omitempty"`
}

func (m *CertificateRevocation) Reset()                    { *m = CertificateRevocation{} }
func (m *CertificateRevocation) String() string            { return proto.CompactTextString(m) }
func (*CertificateRevocation) ProtoMessage()               {}
func (*CertificateRevocation) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{4} }

func (m *CertificateRevocation) GetRevoked() bool {
	if m != nil {
		return m.Revoked
	}
	return false
}

func (m *CertificateRevocation) GetReason() CertificateRevocationReason {
	if m != nil {
		return m.Reason
	}
	return CertificateRevocationReason_CERTIFICATE_REVOCATION_REASON_RESERVED
}

type CertificateAudit struct {
	Mozilla *MozillaSalesForceStatus `protobuf:"bytes,1,opt,name=mozilla" json:"mozilla,omitempty"`
}

func (m *CertificateAudit) Reset()                    { *m = CertificateAudit{} }
func (m *CertificateAudit) String() string            { return proto.CompactTextString(m) }
func (*CertificateAudit) ProtoMessage()               {}
func (*CertificateAudit) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{5} }

func (m *CertificateAudit) GetMozilla() *MozillaSalesForceStatus {
	if m != nil {
		return m.Mozilla
	}
	return nil
}

// Database Records
type Certificate struct {
	Sha1Fp       []byte                 `protobuf:"bytes,1,opt,name=sha1fp,proto3" json:"sha1fp,omitempty"`
	Sha256Fp     []byte                 `protobuf:"bytes,2,opt,name=sha256fp,proto3" json:"sha256fp,omitempty"`
	Raw          []byte                 `protobuf:"bytes,3,opt,name=raw,proto3" json:"raw,omitempty"`
	Parsed       string                 `protobuf:"bytes,4,opt,name=parsed" json:"parsed,omitempty"`
	ParseStatus  CertificateParseStatus `protobuf:"varint,44,opt,name=parse_status,json=parseStatus,enum=zsearch.CertificateParseStatus" json:"parse_status,omitempty"`
	ParseVersion uint32                 `protobuf:"varint,39,opt,name=parse_version,json=parseVersion" json:"parse_version,omitempty"`
	ParseError   string                 `protobuf:"bytes,47,opt,name=parse_error,json=parseError" json:"parse_error,omitempty"`
	Parents      [][]byte               `protobuf:"bytes,5,rep,name=parents,proto3" json:"parents,omitempty"`
	// the chain that we received with the certificate and pass
	// to the certificate processing daemon.
	PresentedChain       [][]byte               `protobuf:"bytes,45,rep,name=presented_chain,json=presentedChain,proto3" json:"presented_chain,omitempty"`
	Source               CertificateSource      `protobuf:"varint,28,opt,name=source,enum=zsearch.CertificateSource" json:"source,omitempty"`
	SeenInScan           bool                   `protobuf:"varint,29,opt,name=seen_in_scan,json=seenInScan" json:"seen_in_scan,omitempty"`
	PostProcessed        bool                   `protobuf:"varint,26,opt,name=post_processed,json=postProcessed" json:"post_processed,omitempty"`
	PostProcessTimestamp uint32                 `protobuf:"varint,37,opt,name=post_process_timestamp,json=postProcessTimestamp" json:"post_process_timestamp,omitempty"`
	Validation           *CertificateValidation `protobuf:"bytes,35,opt,name=validation" json:"validation,omitempty"`
	Ct                   *CTStatus              `protobuf:"bytes,30,opt,name=ct" json:"ct,omitempty"`
	Zlint                *ZLint                 `protobuf:"bytes,38,opt,name=zlint" json:"zlint,omitempty"`
	Revocation           *CertificateRevocation `protobuf:"bytes,43,opt,name=revocation" json:"revocation,omitempty"`
	Audit                *CertificateAudit      `protobuf:"bytes,46,opt,name=audit" json:"audit,omitempty"`
	// store wheter record is precert so that CT synchronization
	// daemon can quickly decide what to do without reparsing the
	// raw certificate
	IsPrecert bool `protobuf:"varint,32,opt,name=is_precert,json=isPrecert" json:"is_precert,omitempty"`
	// store time range that certificate is valid so that cert
	// dump job can mark certificates as expired
	NotValidAfter  uint32 `protobuf:"varint,41,opt,name=not_valid_after,json=notValidAfter" json:"not_valid_after,omitempty"`
	NotValidBefore uint32 `protobuf:"varint,42,opt,name=not_valid_before,json=notValidBefore" json:"not_valid_before,omitempty"`
	Expired        bool   `protobuf:"varint,48,opt,name=expired" json:"expired,omitempty"`
	// deprecated stuff
	InNss                 bool                     `protobuf:"varint,6,opt,name=in_nss,json=inNss" json:"in_nss,omitempty"`
	InMicrosoft           bool                     `protobuf:"varint,7,opt,name=in_microsoft,json=inMicrosoft" json:"in_microsoft,omitempty"`
	InApple               bool                     `protobuf:"varint,8,opt,name=in_apple,json=inApple" json:"in_apple,omitempty"`
	ValidationTimestamp   uint32                   `protobuf:"varint,10,opt,name=validation_timestamp,json=validationTimestamp" json:"validation_timestamp,omitempty"`
	ValidNss              bool                     `protobuf:"varint,11,opt,name=valid_nss,json=validNss" json:"valid_nss,omitempty"`
	ValidMicrosoft        bool                     `protobuf:"varint,12,opt,name=valid_microsoft,json=validMicrosoft" json:"valid_microsoft,omitempty"`
	ValidApple            bool                     `protobuf:"varint,13,opt,name=valid_apple,json=validApple" json:"valid_apple,omitempty"`
	WasValidNss           bool                     `protobuf:"varint,14,opt,name=was_valid_nss,json=wasValidNss" json:"was_valid_nss,omitempty"`
	WasValidMicrosoft     bool                     `protobuf:"varint,15,opt,name=was_valid_microsoft,json=wasValidMicrosoft" json:"was_valid_microsoft,omitempty"`
	WasValidApple         bool                     `protobuf:"varint,16,opt,name=was_valid_apple,json=wasValidApple" json:"was_valid_apple,omitempty"`
	WasInNss              bool                     `protobuf:"varint,17,opt,name=was_in_nss,json=wasInNss" json:"was_in_nss,omitempty"`
	WasInMicrosoft        bool                     `protobuf:"varint,18,opt,name=was_in_microsoft,json=wasInMicrosoft" json:"was_in_microsoft,omitempty"`
	WasInApple            bool                     `protobuf:"varint,19,opt,name=was_in_apple,json=wasInApple" json:"was_in_apple,omitempty"`
	CurrentValidNss       bool                     `protobuf:"varint,20,opt,name=current_valid_nss,json=currentValidNss" json:"current_valid_nss,omitempty"`
	CurrentValidMicrosoft bool                     `protobuf:"varint,21,opt,name=current_valid_microsoft,json=currentValidMicrosoft" json:"current_valid_microsoft,omitempty"`
	CurrentValidApple     bool                     `protobuf:"varint,22,opt,name=current_valid_apple,json=currentValidApple" json:"current_valid_apple,omitempty"`
	CurrentInNss          bool                     `protobuf:"varint,23,opt,name=current_in_nss,json=currentInNss" json:"current_in_nss,omitempty"`
	CurrentInMicrosoft    bool                     `protobuf:"varint,24,opt,name=current_in_microsoft,json=currentInMicrosoft" json:"current_in_microsoft,omitempty"`
	CurrentInApple        bool                     `protobuf:"varint,25,opt,name=current_in_apple,json=currentInApple" json:"current_in_apple,omitempty"`
	NssAudit              *MozillaSalesForceStatus `protobuf:"bytes,31,opt,name=nss_audit,json=nssAudit" json:"nss_audit,omitempty"`
	ShouldPostProcess     bool                     `protobuf:"varint,27,opt,name=should_post_process,json=shouldPostProcess" json:"should_post_process,omitempty"`
	DoNotPostProcess      bool                     `protobuf:"varint,36,opt,name=do_not_post_process,json=doNotPostProcess" json:"do_not_post_process,omitempty"`
}

func (m *Certificate) Reset()                    { *m = Certificate{} }
func (m *Certificate) String() string            { return proto.CompactTextString(m) }
func (*Certificate) ProtoMessage()               {}
func (*Certificate) Descriptor() ([]byte, []int) { return fileDescriptor1, []int{6} }

func (m *Certificate) GetSha1Fp() []byte {
	if m != nil {
		return m.Sha1Fp
	}
	return nil
}

func (m *Certificate) GetSha256Fp() []byte {
	if m != nil {
		return m.Sha256Fp
	}
	return nil
}

func (m *Certificate) GetRaw() []byte {
	if m != nil {
		return m.Raw
	}
	return nil
}

func (m *Certificate) GetParsed() string {
	if m != nil {
		return m.Parsed
	}
	return ""
}

func (m *Certificate) GetParseStatus() CertificateParseStatus {
	if m != nil {
		return m.ParseStatus
	}
	return CertificateParseStatus_CERTIFICATE_PARSE_STATUS_RESERVED
}

func (m *Certificate) GetParseVersion() uint32 {
	if m != nil {
		return m.ParseVersion
	}
	return 0
}

func (m *Certificate) GetParseError() string {
	if m != nil {
		return m.ParseError
	}
	return ""
}

func (m *Certificate) GetParents() [][]byte {
	if m != nil {
		return m.Parents
	}
	return nil
}

func (m *Certificate) GetPresentedChain() [][]byte {
	if m != nil {
		return m.PresentedChain
	}
	return nil
}

func (m *Certificate) GetSource() CertificateSource {
	if m != nil {
		return m.Source
	}
	return CertificateSource_CERTIFICATE_SOURCE_RESERVED
}

func (m *Certificate) GetSeenInScan() bool {
	if m != nil {
		return m.SeenInScan
	}
	return false
}

func (m *Certificate) GetPostProcessed() bool {
	if m != nil {
		return m.PostProcessed
	}
	return false
}

func (m *Certificate) GetPostProcessTimestamp() uint32 {
	if m != nil {
		return m.PostProcessTimestamp
	}
	return 0
}

func (m *Certificate) GetValidation() *CertificateValidation {
	if m != nil {
		return m.Validation
	}
	return nil
}

func (m *Certificate) GetCt() *CTStatus {
	if m != nil {
		return m.Ct
	}
	return nil
}

func (m *Certificate) GetZlint() *ZLint {
	if m != nil {
		return m.Zlint
	}
	return nil
}

func (m *Certificate) GetRevocation() *CertificateRevocation {
	if m != nil {
		return m.Revocation
	}
	return nil
}

func (m *Certificate) GetAudit() *CertificateAudit {
	if m != nil {
		return m.Audit
	}
	return nil
}

func (m *Certificate) GetIsPrecert() bool {
	if m != nil {
		return m.IsPrecert
	}
	return false
}

func (m *Certificate) GetNotValidAfter() uint32 {
	if m != nil {
		return m.NotValidAfter
	}
	return 0
}

func (m *Certificate) GetNotValidBefore() uint32 {
	if m != nil {
		return m.NotValidBefore
	}
	return 0
}

func (m *Certificate) GetExpired() bool {
	if m != nil {
		return m.Expired
	}
	return false
}

func (m *Certificate) GetInNss() bool {
	if m != nil {
		return m.InNss
	}
	return false
}

func (m *Certificate) GetInMicrosoft() bool {
	if m != nil {
		return m.InMicrosoft
	}
	return false
}

func (m *Certificate) GetInApple() bool {
	if m != nil {
		return m.InApple
	}
	return false
}

func (m *Certificate) GetValidationTimestamp() uint32 {
	if m != nil {
		return m.ValidationTimestamp
	}
	return 0
}

func (m *Certificate) GetValidNss() bool {
	if m != nil {
		return m.ValidNss
	}
	return false
}

func (m *Certificate) GetValidMicrosoft() bool {
	if m != nil {
		return m.ValidMicrosoft
	}
	return false
}

func (m *Certificate) GetValidApple() bool {
	if m != nil {
		return m.ValidApple
	}
	return false
}

func (m *Certificate) GetWasValidNss() bool {
	if m != nil {
		return m.WasValidNss
	}
	return false
}

func (m *Certificate) GetWasValidMicrosoft() bool {
	if m != nil {
		return m.WasValidMicrosoft
	}
	return false
}

func (m *Certificate) GetWasValidApple() bool {
	if m != nil {
		return m.WasValidApple
	}
	return false
}

func (m *Certificate) GetWasInNss() bool {
	if m != nil {
		return m.WasInNss
	}
	return false
}

func (m *Certificate) GetWasInMicrosoft() bool {
	if m != nil {
		return m.WasInMicrosoft
	}
	return false
}

func (m *Certificate) GetWasInApple() bool {
	if m != nil {
		return m.WasInApple
	}
	return false
}

func (m *Certificate) GetCurrentValidNss() bool {
	if m != nil {
		return m.CurrentValidNss
	}
	return false
}

func (m *Certificate) GetCurrentValidMicrosoft() bool {
	if m != nil {
		return m.CurrentValidMicrosoft
	}
	return false
}

func (m *Certificate) GetCurrentValidApple() bool {
	if m != nil {
		return m.CurrentValidApple
	}
	return false
}

func (m *Certificate) GetCurrentInNss() bool {
	if m != nil {
		return m.CurrentInNss
	}
	return false
}

func (m *Certificate) GetCurrentInMicrosoft() bool {
	if m != nil {
		return m.CurrentInMicrosoft
	}
	return false
}

func (m *Certificate) GetCurrentInApple() bool {
	if m != nil {
		return m.CurrentInApple
	}
	return false
}

func (m *Certificate) GetNssAudit() *MozillaSalesForceStatus {
	if m != nil {
		return m.NssAudit
	}
	return nil
}

func (m *Certificate) GetShouldPostProcess() bool {
	if m != nil {
		return m.ShouldPostProcess
	}
	return false
}

func (m *Certificate) GetDoNotPostProcess() bool {
	if m != nil {
		return m.DoNotPostProcess
	}
	return false
}

func init() {
	proto.RegisterType((*Path)(nil), "zsearch.Path")
	proto.RegisterType((*RootStoreStatus)(nil), "zsearch.RootStoreStatus")
	proto.RegisterType((*CertificateValidation)(nil), "zsearch.CertificateValidation")
	proto.RegisterType((*MozillaSalesForceStatus)(nil), "zsearch.MozillaSalesForceStatus")
	proto.RegisterType((*CertificateRevocation)(nil), "zsearch.CertificateRevocation")
	proto.RegisterType((*CertificateAudit)(nil), "zsearch.CertificateAudit")
	proto.RegisterType((*Certificate)(nil), "zsearch.Certificate")
	proto.RegisterEnum("zsearch.CertificateType", CertificateType_name, CertificateType_value)
	proto.RegisterEnum("zsearch.CertificateSource", CertificateSource_name, CertificateSource_value)
	proto.RegisterEnum("zsearch.CertificateParseStatus", CertificateParseStatus_name, CertificateParseStatus_value)
	proto.RegisterEnum("zsearch.CertificateRevocationReason", CertificateRevocationReason_name, CertificateRevocationReason_value)
}

func init() { proto.RegisterFile("certificate.proto", fileDescriptor1) }

var fileDescriptor1 = []byte{
	// 1878 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x98, 0xdd, 0x72, 0xdb, 0xb8,
	0x15, 0xc7, 0x2b, 0xc9, 0xb2, 0xa4, 0xa3, 0x2f, 0x0a, 0x76, 0x12, 0xc6, 0xd9, 0x24, 0x8a, 0xe3,
	0x24, 0x8e, 0xe2, 0x38, 0x1b, 0x35, 0xbb, 0xed, 0xec, 0x74, 0x3a, 0xc3, 0x50, 0xd4, 0x9a, 0xb3,
	0xb2, 0xa4, 0x21, 0x65, 0x67, 0x76, 0x6f, 0x38, 0x08, 0x85, 0xac, 0xd8, 0x95, 0x48, 0x0e, 0x41,
	0xc7, 0x4d, 0xae, 0xfb, 0x2e, 0x7d, 0x84, 0x5e, 0xf5, 0x29, 0x7a, 0xd1, 0x87, 0xe8, 0x6d, 0x1f,
	0xa0, 0x03, 0x80, 0x22, 0x28, 0x5b, 0x96, 0x7b, 0x65, 0xe1, 0x9c, 0xdf, 0x01, 0xff, 0x38, 0x38,
	0x38, 0xc0, 0x18, 0x5a, 0x2e, 0x89, 0x62, 0xef, 0x93, 0xe7, 0xe2, 0x98, 0x1c, 0x87, 0x51, 0x10,
	0x07, 0xa8, 0xf4, 0x95, 0x12, 0x1c, 0xb9, 0xb3, 0xbd, 0x9a, 0x1b, 0x2c, 0x16, 0x81, 0x2f, 0xcc,
	0x7b, 0xd5, 0xaf, 0x73, 0xcf, 0x8f, 0x93, 0x41, 0xd9, 0x4d, 0x7e, 0xed, 0xef, 0xc3, 0xd6, 0x18,
	0xc7, 0x33, 0xb4, 0x07, 0x65, 0x3a, 0xc3, 0xdd, 0xef, 0xbe, 0xff, 0x14, 0xaa, 0xb9, 0x76, 0xe1,
	0xb0, 0x66, 0xa5, 0xe3, 0xfd, 0xbf, 0x15, 0xa0, 0x69, 0x05, 0x41, 0x6c, 0xc7, 0x41, 0x44, 0xec,
	0x18, 0xc7, 0x17, 0x14, 0xed, 0x42, 0xf1, 0x33, 0x9e, 0x7b, 0x53, 0x35, 0xd7, 0xce, 0x1d, 0x96,
	0x2d, 0x31, 0x40, 0x0f, 0xa0, 0x72, 0x89, 0xa9, 0x23, 0x3c, 0x79, 0xee, 0x29, 0x5f, 0x62, 0x7a,
	0xce, 0x9d, 0x87, 0xa0, 0xcc, 0x30, 0x75, 0xe2, 0xe8, 0x82, 0xc6, 0x64, 0xea, 0x84, 0x38, 0x9e,
	0xa9, 0x05, 0xce, 0x34, 0x66, 0x98, 0x4e, 0x84, 0x99, 0x8b, 0xe1, 0xe4, 0x74, 0x95, 0xdc, 0x5a,
	0x92, 0xd3, 0x2c, 0xd9, 0x86, 0xea, 0xc7, 0x39, 0x76, 0x7f, 0x9b, 0x7b, 0xcc, 0xa4, 0x16, 0x39,
	0x94, 0x35, 0x31, 0xe2, 0x72, 0xe6, 0xc5, 0x24, 0x21, 0xb6, 0x05, 0x91, 0x31, 0xa1, 0x23, 0xd8,
	0x8a, 0xbf, 0x84, 0x44, 0x2d, 0xb5, 0x73, 0x87, 0x8d, 0xae, 0x7a, 0x9c, 0xe4, 0xef, 0x58, 0x97,
	0xa9, 0x9d, 0x7c, 0x09, 0x89, 0xc5, 0x29, 0xd4, 0x85, 0x7a, 0x56, 0x17, 0x55, 0xcb, 0xed, 0xc2,
	0x61, 0xb5, 0x5b, 0x4f, 0xc3, 0x98, 0x2e, 0xab, 0x16, 0x4b, 0x91, 0x14, 0x75, 0xa0, 0xe5, 0xf9,
	0x4e, 0x44, 0x3e, 0x07, 0x2e, 0x8e, 0xbd, 0xc0, 0x77, 0x28, 0x89, 0xd5, 0x0a, 0x57, 0xd2, 0xf4,
	0x7c, 0x2b, 0xb5, 0xdb, 0x24, 0x46, 0x2a, 0x94, 0x42, 0x1c, 0x11, 0x3f, 0xa6, 0x2a, 0xf0, 0x7d,
	0x58, 0x0e, 0xf7, 0xff, 0x95, 0x87, 0x3b, 0x19, 0x4d, 0x3c, 0xa9, 0x3c, 0x0c, 0x75, 0xa0, 0xe0,
	0x53, 0xca, 0xb7, 0xa2, 0x9a, 0x59, 0xc0, 0x95, 0x3d, 0xb3, 0x18, 0x84, 0xbe, 0x87, 0xca, 0xc2,
	0x73, 0xa3, 0x80, 0x06, 0x9f, 0x62, 0xbe, 0x45, 0x9b, 0x22, 0x24, 0x8a, 0x8e, 0xa1, 0x88, 0xc3,
	0x70, 0x4e, 0xf8, 0x96, 0x6d, 0x8a, 0x11, 0x18, 0xcb, 0xea, 0x5f, 0xf0, 0x67, 0xcc, 0xf7, 0x6d,
	0x13, 0xce, 0x29, 0xd4, 0x85, 0x12, 0xf6, 0xa7, 0x51, 0xe0, 0x89, 0x3d, 0xdc, 0x14, 0xb0, 0x04,
	0x51, 0x0f, 0x5a, 0xbf, 0x06, 0xc1, 0xaf, 0x73, 0xe2, 0xb8, 0xb1, 0x13, 0x46, 0xde, 0x02, 0x47,
	0x5f, 0x54, 0xb8, 0x25, 0xba, 0x29, 0x42, 0xf4, 0x78, 0x2c, 0x02, 0xf6, 0xff, 0x53, 0x80, 0x7b,
	0xa7, 0xc1, 0x57, 0x6f, 0x3e, 0xc7, 0x36, 0x9e, 0x13, 0xda, 0x0f, 0x22, 0x77, 0x59, 0xe4, 0x0f,
	0x01, 0xdc, 0x8b, 0x88, 0x65, 0xdf, 0xf1, 0xfc, 0xa4, 0xd2, 0x2b, 0x89, 0xc5, 0xf4, 0xd1, 0x1d,
	0xd8, 0x66, 0xd5, 0xee, 0xf9, 0x49, 0xa9, 0x17, 0x2f, 0x31, 0x35, 0x7d, 0x16, 0x15, 0x5c, 0xfa,
	0x24, 0x72, 0x7c, 0xbc, 0x10, 0xe9, 0xaa, 0x58, 0x15, 0x6e, 0x19, 0xe2, 0x05, 0x41, 0x8f, 0xa1,
	0x2a, 0x76, 0x54, 0xf8, 0xb7, 0xb8, 0x1f, 0x84, 0x89, 0x03, 0x2f, 0x41, 0xc9, 0x9c, 0x6a, 0x41,
	0x15, 0x39, 0xd5, 0xcc, 0xd8, 0x39, 0xfa, 0x1a, 0x50, 0x16, 0x0d, 0x83, 0xb9, 0xe7, 0x7e, 0xe1,
	0x35, 0x5e, 0xb1, 0xb2, 0xad, 0x61, 0xcc, 0x1d, 0xe8, 0x04, 0xda, 0xd2, 0xc8, 0xea, 0x30, 0x8c,
	0xb0, 0x1b, 0x7b, 0x2e, 0x71, 0x68, 0x8c, 0x63, 0xb2, 0x20, 0x7e, 0xcc, 0x4f, 0x41, 0xc5, 0x7a,
	0xb4, 0xc2, 0x8d, 0x13, 0xcc, 0x5e, 0x52, 0xe8, 0x25, 0xb4, 0xdc, 0xd0, 0xa1, 0x78, 0x41, 0x1c,
	0x4c, 0x1d, 0x21, 0x5e, 0x2d, 0x8b, 0x23, 0xea, 0x86, 0x36, 0x5e, 0x10, 0x8d, 0x8e, 0xb9, 0x15,
	0xbd, 0x81, 0x5d, 0x7c, 0x31, 0xf5, 0xe2, 0xab, 0xb4, 0xa8, 0xff, 0x16, 0xf7, 0xad, 0x04, 0x3c,
	0x83, 0x06, 0x8d, 0xb1, 0x3f, 0xc5, 0xd1, 0xd4, 0xe1, 0x5e, 0xbe, 0xa9, 0x15, 0xab, 0xbe, 0xb4,
	0x6a, 0xcc, 0x88, 0xee, 0x43, 0xf9, 0x63, 0x94, 0x00, 0x55, 0x0e, 0x94, 0x3e, 0x46, 0xc2, 0xa5,
	0x42, 0x89, 0xdb, 0x83, 0x48, 0xad, 0x09, 0x4f, 0x32, 0xdc, 0x0f, 0x56, 0x8e, 0x90, 0x3c, 0x79,
	0x2c, 0x84, 0x9d, 0xcf, 0xdf, 0xc8, 0xb2, 0xa3, 0x2d, 0x87, 0xe8, 0x4f, 0xb0, 0x1d, 0x11, 0x4c,
	0x03, 0xb1, 0xcb, 0x8d, 0xee, 0xc1, 0xba, 0x06, 0x21, 0x67, 0xb2, 0x38, 0x6b, 0x25, 0x31, 0xfb,
	0x43, 0x50, 0x32, 0x98, 0x90, 0xf7, 0x03, 0x94, 0x16, 0xa2, 0xe2, 0x92, 0x23, 0xdb, 0x4e, 0xa7,
	0xbc, 0xa1, 0x12, 0xad, 0x65, 0xc0, 0xfe, 0x3f, 0x1b, 0x50, 0xcd, 0x4c, 0x88, 0xee, 0xc2, 0x36,
	0x9d, 0xe1, 0xb7, 0xbc, 0x6b, 0xe7, 0x0e, 0x6b, 0x56, 0x32, 0x5a, 0xe9, 0xe7, 0x79, 0xee, 0x49,
	0xc7, 0x48, 0x81, 0x42, 0x84, 0x2f, 0x79, 0x65, 0xd6, 0x2c, 0xf6, 0x93, 0xcd, 0x12, 0xe2, 0x88,
	0x92, 0x69, 0x52, 0x8e, 0xc9, 0x08, 0xbd, 0x87, 0x1a, 0xff, 0xc5, 0xeb, 0xe3, 0x82, 0xaa, 0x47,
	0x3c, 0x03, 0x8f, 0xd7, 0x65, 0x60, 0xcc, 0xb8, 0x44, 0x6d, 0x35, 0x94, 0x03, 0xf4, 0x14, 0xea,
	0x62, 0x8e, 0xcf, 0x24, 0xa2, 0x5e, 0xe0, 0xab, 0x2f, 0xda, 0xb9, 0xc3, 0xba, 0x25, 0x26, 0x3e,
	0x17, 0xb6, 0xe4, 0x50, 0x50, 0xe2, 0x90, 0x28, 0x0a, 0x22, 0xf5, 0x4d, 0x7a, 0x28, 0x28, 0x31,
	0x98, 0x25, 0xdb, 0x16, 0x8b, 0x2b, 0x6d, 0x11, 0xbd, 0x80, 0x66, 0x18, 0x11, 0x4a, 0x7c, 0xd6,
	0x92, 0xdd, 0x19, 0xf6, 0x7c, 0xf5, 0x35, 0x27, 0x1a, 0xa9, 0x59, 0x67, 0x56, 0xd4, 0x85, 0x6d,
	0x1a, 0x5c, 0x44, 0x2e, 0x51, 0xbf, 0xe1, 0xcb, 0xd8, 0x5b, 0xb7, 0x0c, 0x9b, 0x13, 0x56, 0x42,
	0xa2, 0x36, 0xd4, 0x28, 0x21, 0xbe, 0xe3, 0xf9, 0x0e, 0x75, 0xb1, 0xaf, 0x3e, 0xe4, 0xb5, 0x01,
	0xcc, 0x66, 0xfa, 0xb6, 0x8b, 0x7d, 0x56, 0xad, 0x61, 0x40, 0x59, 0x03, 0x0a, 0x5c, 0x42, 0x59,
	0x0a, 0xf7, 0x38, 0x53, 0x67, 0xd6, 0xf1, 0xd2, 0x88, 0xde, 0xc1, 0xdd, 0x2c, 0xe6, 0xc4, 0xde,
	0x82, 0xd0, 0x18, 0x2f, 0x42, 0xf5, 0x19, 0x4f, 0xc7, 0x6e, 0x06, 0x9f, 0x2c, 0x7d, 0xe8, 0xcf,
	0x00, 0x9f, 0xd3, 0x36, 0xaf, 0x3e, 0xe5, 0xc5, 0xf2, 0x68, 0x9d, 0x6c, 0x79, 0x19, 0x58, 0x99,
	0x08, 0xf4, 0x04, 0xf2, 0x6e, 0xac, 0x3e, 0xe2, 0x71, 0x2d, 0x19, 0x37, 0x49, 0xf6, 0x29, 0xef,
	0xc6, 0xe8, 0x00, 0x8a, 0xfc, 0x65, 0xa0, 0x3e, 0xe7, 0x54, 0x23, 0xa5, 0x7e, 0x19, 0x78, 0x7e,
	0x6c, 0x09, 0x27, 0x13, 0x22, 0xaf, 0x2f, 0xf5, 0xd5, 0xcd, 0x42, 0x32, 0x07, 0x21, 0x13, 0x81,
	0xde, 0x40, 0x51, 0x9c, 0xd4, 0x63, 0x1e, 0x7a, 0x7f, 0x5d, 0x28, 0x3f, 0x1c, 0x96, 0xe0, 0x58,
	0x13, 0xf5, 0xa8, 0x13, 0x46, 0x84, 0x35, 0x22, 0xb5, 0x2d, 0x5a, 0xaf, 0x47, 0xc7, 0xc2, 0x80,
	0x9e, 0x43, 0xd3, 0x0f, 0x62, 0xf1, 0xd0, 0x70, 0xf0, 0xa7, 0x98, 0x44, 0xea, 0x4b, 0x9e, 0xc7,
	0xba, 0x1f, 0xc4, 0x3c, 0x19, 0x1a, 0x33, 0xb2, 0x97, 0x84, 0xe4, 0x3e, 0x92, 0x4f, 0x41, 0x44,
	0xd4, 0x0e, 0x07, 0x1b, 0x4b, 0xf0, 0x3d, 0xb7, 0xb2, 0x02, 0x23, 0x7f, 0x0d, 0xbd, 0x88, 0x4c,
	0xd5, 0x6f, 0x45, 0x03, 0x48, 0x86, 0xac, 0xcd, 0x7b, 0xbe, 0xc3, 0x2e, 0x58, 0xf1, 0x78, 0x28,
	0x7a, 0xfe, 0x90, 0x52, 0xf4, 0x0c, 0x6a, 0x9e, 0xef, 0xc8, 0xbb, 0x94, 0x35, 0xce, 0xf2, 0xfb,
	0xbc, 0x9a, 0xb3, 0xaa, 0x9e, 0x7f, 0x9a, 0xde, 0x9b, 0x0f, 0xa1, 0xec, 0xf9, 0x8e, 0xb8, 0x3a,
	0xcb, 0x29, 0x52, 0xf2, 0x7c, 0x8d, 0x5f, 0x93, 0x6f, 0x61, 0x57, 0xee, 0x57, 0xa6, 0x2a, 0x80,
	0x8b, 0xdc, 0x91, 0x3e, 0x59, 0x14, 0x8f, 0xa1, 0x22, 0xd6, 0xc3, 0x24, 0x55, 0xd3, 0x29, 0xcb,
	0xdc, 0xc8, 0x94, 0xbd, 0x82, 0xa6, 0x00, 0xa4, 0xb8, 0x5a, 0x8a, 0x35, 0xb8, 0x4b, 0xea, 0x7b,
	0x0a, 0xd5, 0x24, 0x8b, 0x5c, 0x62, 0x3d, 0x05, 0x45, 0x1d, 0x09, 0x95, 0xfb, 0x50, 0x4f, 0xdf,
	0x75, 0xfc, 0xb3, 0x8d, 0xe4, 0x19, 0x95, 0xbc, 0xed, 0xd8, 0x57, 0xbb, 0xb0, 0x23, 0x19, 0xf9,
	0xe5, 0x66, 0x3a, 0x61, 0x6b, 0x49, 0xcb, 0x8f, 0x77, 0xa0, 0x29, 0x63, 0x84, 0x00, 0x25, 0xe5,
	0xeb, 0x4b, 0x5e, 0x68, 0x68, 0x03, 0x88, 0xdb, 0x96, 0x0b, 0x68, 0xc9, 0x75, 0xf3, 0x5b, 0x97,
	0x29, 0x38, 0x02, 0x25, 0x21, 0xe4, 0xe7, 0x91, 0x5c, 0x38, 0xe7, 0xe4, 0xb7, 0x0f, 0xa0, 0x96,
	0xd0, 0xe2, 0xc3, 0x3b, 0x72, 0xe5, 0x9c, 0x14, 0x5f, 0xed, 0x40, 0x6b, 0xf9, 0x04, 0x90, 0xab,
	0xdf, 0x15, 0x4f, 0xb7, 0xc4, 0x91, 0x66, 0xe0, 0x07, 0xb8, 0xb7, 0xca, 0x4a, 0x19, 0x77, 0xd2,
	0xc9, 0xef, 0x64, 0xa3, 0xa4, 0x9a, 0x2e, 0xec, 0xac, 0xc6, 0x0a, 0x51, 0x77, 0x65, 0xf6, 0xb2,
	0x71, 0x42, 0xdb, 0x01, 0x34, 0xe4, 0xf3, 0x84, 0x0b, 0xbb, 0xc7, 0x85, 0xd5, 0xd2, 0x27, 0x0a,
	0x53, 0xf5, 0x0e, 0x76, 0x33, 0x94, 0x94, 0xa4, 0xa6, 0x53, 0xa3, 0x94, 0x97, 0x7a, 0x8e, 0x40,
	0xc9, 0x44, 0x09, 0x31, 0xf7, 0x65, 0x2e, 0xd3, 0x08, 0xa1, 0x44, 0x83, 0x8a, 0x4f, 0x69, 0x72,
	0x19, 0x3f, 0xfe, 0xff, 0xee, 0x34, 0xb1, 0x79, 0x3e, 0xa5, 0xe2, 0x52, 0xec, 0xc2, 0x0e, 0x9d,
	0x05, 0x17, 0xf3, 0xa9, 0x93, 0xed, 0x93, 0xea, 0x03, 0x99, 0x00, 0xe1, 0x1e, 0xcb, 0x3e, 0x89,
	0xde, 0xc2, 0xce, 0x34, 0x70, 0xd8, 0x01, 0x5f, 0x89, 0x39, 0x48, 0x63, 0x94, 0x69, 0x30, 0x0c,
	0xe2, 0x4c, 0x48, 0xe7, 0xef, 0x39, 0x68, 0x5e, 0x79, 0xd8, 0xa3, 0x87, 0x70, 0x5f, 0x37, 0xac,
	0x89, 0xd9, 0x37, 0x75, 0x6d, 0x62, 0x38, 0x93, 0x9f, 0xc7, 0x86, 0x63, 0x19, 0xb6, 0x61, 0x9d,
	0x1b, 0x3d, 0xe5, 0x77, 0xe8, 0x1b, 0x50, 0xaf, 0xb9, 0xcf, 0x86, 0x3f, 0x0d, 0x47, 0x1f, 0x86,
	0x4a, 0x0e, 0xdd, 0x87, 0x3b, 0xd7, 0xbc, 0x03, 0x43, 0xeb, 0x2b, 0x79, 0xf4, 0x04, 0x1e, 0x5e,
	0x73, 0x99, 0xc3, 0x89, 0x61, 0x9d, 0x1a, 0x3d, 0x53, 0x9b, 0x18, 0x4a, 0x61, 0x6d, 0xb4, 0x35,
	0x1a, 0x4d, 0x94, 0xad, 0xce, 0x3f, 0xf2, 0xd0, 0xba, 0x76, 0x31, 0xa1, 0xc7, 0xf0, 0x20, 0x1b,
	0x60, 0x8f, 0xce, 0x2c, 0x7d, 0x45, 0xed, 0x23, 0xd8, 0x5b, 0x03, 0x48, 0xbd, 0x0f, 0xe0, 0xde,
	0x1a, 0xbf, 0xad, 0x6b, 0x43, 0x25, 0x7f, 0x55, 0x4e, 0xe2, 0xd4, 0x27, 0x4a, 0x01, 0xbd, 0x84,
	0x67, 0x6b, 0x5c, 0xa7, 0xa3, 0x5f, 0xcc, 0xc1, 0x40, 0x73, 0x6c, 0x6d, 0x60, 0xd8, 0xfd, 0x91,
	0xa5, 0x1b, 0xca, 0xd6, 0x06, 0x8d, 0x9a, 0xa5, 0x9f, 0x28, 0xc5, 0xab, 0x09, 0x5f, 0x02, 0xda,
	0xd8, 0xec, 0xfd, 0x41, 0xd9, 0xbe, 0xc1, 0x7d, 0x72, 0xf6, 0xfe, 0xfd, 0xc0, 0x50, 0x4a, 0x37,
	0x4c, 0xaf, 0x4f, 0x1c, 0xfd, 0x44, 0x33, 0x87, 0x4a, 0xb9, 0xf3, 0xef, 0x1c, 0xdc, 0x5d, 0xff,
	0x32, 0x41, 0xcf, 0xe0, 0x49, 0x36, 0x76, 0xac, 0x59, 0xb6, 0xe1, 0xd8, 0x13, 0x6d, 0x72, 0x66,
	0x67, 0x93, 0x78, 0x00, 0xed, 0x1b, 0x31, 0x99, 0xca, 0x4d, 0x94, 0x7d, 0xa6, 0xeb, 0x86, 0x6d,
	0x5f, 0xaf, 0x82, 0x15, 0xaa, 0xaf, 0x99, 0x03, 0xa5, 0x80, 0x5e, 0xc0, 0xd3, 0x1b, 0x91, 0xe1,
	0x68, 0x22, 0x0c, 0x3d, 0x65, 0xab, 0xf3, 0xdf, 0x2d, 0x78, 0xb0, 0xe1, 0xd5, 0x89, 0x3a, 0xf0,
	0x3c, 0x3b, 0x91, 0x65, 0x9c, 0x8f, 0x74, 0x6d, 0x62, 0x8e, 0x86, 0x8e, 0x65, 0x68, 0x36, 0xff,
	0x93, 0xae, 0xf1, 0xca, 0x86, 0x5e, 0x67, 0xe5, 0x42, 0x5f, 0xc3, 0xcb, 0xdb, 0x50, 0x7b, 0x6c,
	0xe8, 0x66, 0xdf, 0x34, 0x7a, 0x4a, 0x1e, 0x7d, 0x0b, 0x47, 0x9b, 0xf1, 0x9f, 0x8c, 0x9f, 0x1d,
	0x7d, 0x74, 0x3a, 0xb6, 0x46, 0xa7, 0xa6, 0xcd, 0x8e, 0xc1, 0x1b, 0x78, 0xb5, 0x39, 0x42, 0xd7,
	0xb2, 0x01, 0x5b, 0xe8, 0x3b, 0x78, 0xbb, 0x39, 0x40, 0xeb, 0xf7, 0xcd, 0x81, 0x29, 0x4c, 0xfa,
	0x89, 0x36, 0xfc, 0xd1, 0xe8, 0x29, 0x45, 0x74, 0x04, 0x87, 0x9b, 0xc3, 0xec, 0xb3, 0xb1, 0xc1,
	0x72, 0x6d, 0xf4, 0x94, 0x6d, 0xf4, 0x47, 0x78, 0x77, 0x8b, 0x2a, 0xc3, 0xb6, 0x85, 0x61, 0xd4,
	0x77, 0x46, 0x63, 0xc3, 0xe2, 0x03, 0xa5, 0x84, 0xba, 0x70, 0x7c, 0x5b, 0xa4, 0xf4, 0x9e, 0x8c,
	0x06, 0x3d, 0xa5, 0x8c, 0xde, 0xc2, 0xeb, 0xdb, 0xf6, 0xee, 0x74, 0x74, 0x6e, 0x38, 0x7d, 0x6b,
	0x74, 0xea, 0xe8, 0xd6, 0x40, 0xa9, 0xdc, 0x9e, 0x85, 0xb1, 0x65, 0x9e, 0x9b, 0x03, 0xe3, 0x47,
	0xc3, 0xf9, 0x60, 0x4e, 0x4e, 0x7a, 0x96, 0xf6, 0x61, 0xa8, 0xc0, 0xed, 0xd9, 0xd6, 0x56, 0xb2,
	0x5d, 0xfd, 0xb8, 0xcd, 0xff, 0x57, 0xf4, 0xfb, 0xff, 0x05, 0x00, 0x00, 0xff, 0xff, 0xb8, 0xee,
	0x7c, 0x10, 0x6e, 0x12, 0x00, 0x00,
}
