// Code generated by protoc-gen-go.
// source: ct.proto
// DO NOT EDIT!

package censys_definitions

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type CTPushStatus int32

const (
	CTPushStatus_CT_PUSH_STATUS_RESERVED       CTPushStatus = 0
	CTPushStatus_CT_PUSH_STATUS_UNKNOWN        CTPushStatus = 1
	CTPushStatus_CT_PUSH_STATUS_SUCCESS        CTPushStatus = 2
	CTPushStatus_CT_PUSH_STATUS_UNKNOWN_ERROR  CTPushStatus = 3
	CTPushStatus_CT_PUSH_STATUS_INVALID_ROOT   CTPushStatus = 4
	CTPushStatus_CT_PUSH_STATUS_ALREADY_EXISTS CTPushStatus = 5
	CTPushStatus_CT_PUSH_STATUS_WILL_NOT_PUSH  CTPushStatus = 6
)

var CTPushStatus_name = map[int32]string{
	0: "CT_PUSH_STATUS_RESERVED",
	1: "CT_PUSH_STATUS_UNKNOWN",
	2: "CT_PUSH_STATUS_SUCCESS",
	3: "CT_PUSH_STATUS_UNKNOWN_ERROR",
	4: "CT_PUSH_STATUS_INVALID_ROOT",
	5: "CT_PUSH_STATUS_ALREADY_EXISTS",
	6: "CT_PUSH_STATUS_WILL_NOT_PUSH",
}
var CTPushStatus_value = map[string]int32{
	"CT_PUSH_STATUS_RESERVED":       0,
	"CT_PUSH_STATUS_UNKNOWN":        1,
	"CT_PUSH_STATUS_SUCCESS":        2,
	"CT_PUSH_STATUS_UNKNOWN_ERROR":  3,
	"CT_PUSH_STATUS_INVALID_ROOT":   4,
	"CT_PUSH_STATUS_ALREADY_EXISTS": 5,
	"CT_PUSH_STATUS_WILL_NOT_PUSH":  6,
}

func (x CTPushStatus) String() string {
	return proto.EnumName(CTPushStatus_name, int32(x))
}
func (CTPushStatus) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

type CTServer int32

const (
	CTServer_CT_SERVER_RESERVED CTServer = 0
	// Censys
	CTServer_CT_SERVER_CENSYS_DEVELOPMENT CTServer = 1
	CTServer_CT_SERVER_CENSYS_PRODUCTION  CTServer = 2
	// Google
	CTServer_CT_SERVER_GOOGLE_AVIATOR    CTServer = 10
	CTServer_CT_SERVER_GOOGLE_PILOT      CTServer = 11
	CTServer_CT_SERVER_GOOGLE_ROCKETEER  CTServer = 12
	CTServer_CT_SERVER_GOOGLE_SUBMARINER CTServer = 13
	CTServer_CT_SERVER_GOOGLE_TESTTUBE   CTServer = 14
	CTServer_CT_SERVER_GOOGLE_ICARUS     CTServer = 15
	CTServer_CT_SERVER_GOOGLE_SKYDIVER   CTServer = 16
	CTServer_CT_SERVER_GOOGLE_DAEDALUS   CTServer = 17
	// Google Argon
	CTServer_CT_SERVER_GOOGLE_ARGON_2017 CTServer = 50
	CTServer_CT_SERVER_GOOGLE_ARGON_2018 CTServer = 51
	CTServer_CT_SERVER_GOOGLE_ARGON_2019 CTServer = 52
	CTServer_CT_SERVER_GOOGLE_ARGON_2020 CTServer = 53
	CTServer_CT_SERVER_GOOGLE_ARGON_2021 CTServer = 54
	// Cloudflare Nimbus
	CTServer_CT_SERVER_CLOUDFLARE_NIMBUS_2017 CTServer = 60
	CTServer_CT_SERVER_CLOUDFLARE_NIMBUS_2018 CTServer = 61
	CTServer_CT_SERVER_CLOUDFLARE_NIMBUS_2019 CTServer = 62
	CTServer_CT_SERVER_CLOUDFLARE_NIMBUS_2020 CTServer = 63
	CTServer_CT_SERVER_CLOUDFLARE_NIMBUS_2021 CTServer = 64
	// Digicert
	CTServer_CT_SERVER_DIGICERT_CT1 CTServer = 20
	CTServer_CT_SERVER_DIGICERT_CT2 CTServer = 40
	// Izenpe
	CTServer_CT_SERVER_IZENPE_COM_CT CTServer = 21
	CTServer_CT_SERVER_IZENPE_EUS_CT CTServer = 22
	// Symantec
	CTServer_CT_SERVER_SYMANTEC_WS_CT     CTServer = 23
	CTServer_CT_SERVER_SYMANTEC_WS_VEGA   CTServer = 24
	CTServer_CT_SERVER_SYMANTEC_WS_SIRIUS CTServer = 37
	CTServer_CT_SERVER_SYMANTEC_WS_DENEB  CTServer = 32
	// Comodo
	CTServer_CT_SERVER_COMODO_DODO    CTServer = 35
	CTServer_CT_SERVER_COMODO_MAMMOTH CTServer = 36
	CTServer_CT_SERVER_COMODO_SABRE   CTServer = 41
	// Wosign, StartCom, and WoTrus
	CTServer_CT_SERVER_WOSIGN_CTLOG  CTServer = 25
	CTServer_CT_SERVER_WOSIGN_CT     CTServer = 26
	CTServer_CT_SERVER_WOTRUS_CTLOG  CTServer = 47
	CTServer_CT_SERVER_WOTRUS_CTLOG3 CTServer = 48
	CTServer_CT_SERVER_STARTSSL_CT   CTServer = 29
	// GDCA
	CTServer_CT_SERVER_GDCA_CT    CTServer = 28
	CTServer_CT_SERVER_GDCA_CTLOG CTServer = 34
	CTServer_CT_SERVER_GDCA_LOG   CTServer = 45
	CTServer_CT_SERVER_GDCA_LOG2  CTServer = 46
	// Venafi
	CTServer_CT_SERVER_VENAFI_API_CTLOG      CTServer = 31
	CTServer_CT_SERVER_VENAFI_API_CTLOG_GEN2 CTServer = 39
	// Nordu
	CTServer_CT_SERVER_NORDU_CT_PLAUSIBLE CTServer = 33
	// Let's Encrypt
	CTServer_CT_SERVER_LETSENCRYPT_CT_CLICKY CTServer = 43
	// Other
	CTServer_CT_SERVER_CERTLY_LOG                    CTServer = 30
	CTServer_CT_SERVER_CNNIC_CTSERVER                CTServer = 27
	CTServer_CT_SERVER_CERTIFICATETRANSPARENCY_CN_CT CTServer = 38
	CTServer_CT_SERVER_SHECA_CT                      CTServer = 42
	CTServer_CT_SERVER_BEHIND_THE_SOFA               CTServer = 44
)

var CTServer_name = map[int32]string{
	0:  "CT_SERVER_RESERVED",
	1:  "CT_SERVER_CENSYS_DEVELOPMENT",
	2:  "CT_SERVER_CENSYS_PRODUCTION",
	10: "CT_SERVER_GOOGLE_AVIATOR",
	11: "CT_SERVER_GOOGLE_PILOT",
	12: "CT_SERVER_GOOGLE_ROCKETEER",
	13: "CT_SERVER_GOOGLE_SUBMARINER",
	14: "CT_SERVER_GOOGLE_TESTTUBE",
	15: "CT_SERVER_GOOGLE_ICARUS",
	16: "CT_SERVER_GOOGLE_SKYDIVER",
	17: "CT_SERVER_GOOGLE_DAEDALUS",
	50: "CT_SERVER_GOOGLE_ARGON_2017",
	51: "CT_SERVER_GOOGLE_ARGON_2018",
	52: "CT_SERVER_GOOGLE_ARGON_2019",
	53: "CT_SERVER_GOOGLE_ARGON_2020",
	54: "CT_SERVER_GOOGLE_ARGON_2021",
	60: "CT_SERVER_CLOUDFLARE_NIMBUS_2017",
	61: "CT_SERVER_CLOUDFLARE_NIMBUS_2018",
	62: "CT_SERVER_CLOUDFLARE_NIMBUS_2019",
	63: "CT_SERVER_CLOUDFLARE_NIMBUS_2020",
	64: "CT_SERVER_CLOUDFLARE_NIMBUS_2021",
	20: "CT_SERVER_DIGICERT_CT1",
	40: "CT_SERVER_DIGICERT_CT2",
	21: "CT_SERVER_IZENPE_COM_CT",
	22: "CT_SERVER_IZENPE_EUS_CT",
	23: "CT_SERVER_SYMANTEC_WS_CT",
	24: "CT_SERVER_SYMANTEC_WS_VEGA",
	37: "CT_SERVER_SYMANTEC_WS_SIRIUS",
	32: "CT_SERVER_SYMANTEC_WS_DENEB",
	35: "CT_SERVER_COMODO_DODO",
	36: "CT_SERVER_COMODO_MAMMOTH",
	41: "CT_SERVER_COMODO_SABRE",
	25: "CT_SERVER_WOSIGN_CTLOG",
	26: "CT_SERVER_WOSIGN_CT",
	47: "CT_SERVER_WOTRUS_CTLOG",
	48: "CT_SERVER_WOTRUS_CTLOG3",
	29: "CT_SERVER_STARTSSL_CT",
	28: "CT_SERVER_GDCA_CT",
	34: "CT_SERVER_GDCA_CTLOG",
	45: "CT_SERVER_GDCA_LOG",
	46: "CT_SERVER_GDCA_LOG2",
	31: "CT_SERVER_VENAFI_API_CTLOG",
	39: "CT_SERVER_VENAFI_API_CTLOG_GEN2",
	33: "CT_SERVER_NORDU_CT_PLAUSIBLE",
	43: "CT_SERVER_LETSENCRYPT_CT_CLICKY",
	30: "CT_SERVER_CERTLY_LOG",
	27: "CT_SERVER_CNNIC_CTSERVER",
	38: "CT_SERVER_CERTIFICATETRANSPARENCY_CN_CT",
	42: "CT_SERVER_SHECA_CT",
	44: "CT_SERVER_BEHIND_THE_SOFA",
}
var CTServer_value = map[string]int32{
	"CT_SERVER_RESERVED":                      0,
	"CT_SERVER_CENSYS_DEVELOPMENT":            1,
	"CT_SERVER_CENSYS_PRODUCTION":             2,
	"CT_SERVER_GOOGLE_AVIATOR":                10,
	"CT_SERVER_GOOGLE_PILOT":                  11,
	"CT_SERVER_GOOGLE_ROCKETEER":              12,
	"CT_SERVER_GOOGLE_SUBMARINER":             13,
	"CT_SERVER_GOOGLE_TESTTUBE":               14,
	"CT_SERVER_GOOGLE_ICARUS":                 15,
	"CT_SERVER_GOOGLE_SKYDIVER":               16,
	"CT_SERVER_GOOGLE_DAEDALUS":               17,
	"CT_SERVER_GOOGLE_ARGON_2017":             50,
	"CT_SERVER_GOOGLE_ARGON_2018":             51,
	"CT_SERVER_GOOGLE_ARGON_2019":             52,
	"CT_SERVER_GOOGLE_ARGON_2020":             53,
	"CT_SERVER_GOOGLE_ARGON_2021":             54,
	"CT_SERVER_CLOUDFLARE_NIMBUS_2017":        60,
	"CT_SERVER_CLOUDFLARE_NIMBUS_2018":        61,
	"CT_SERVER_CLOUDFLARE_NIMBUS_2019":        62,
	"CT_SERVER_CLOUDFLARE_NIMBUS_2020":        63,
	"CT_SERVER_CLOUDFLARE_NIMBUS_2021":        64,
	"CT_SERVER_DIGICERT_CT1":                  20,
	"CT_SERVER_DIGICERT_CT2":                  40,
	"CT_SERVER_IZENPE_COM_CT":                 21,
	"CT_SERVER_IZENPE_EUS_CT":                 22,
	"CT_SERVER_SYMANTEC_WS_CT":                23,
	"CT_SERVER_SYMANTEC_WS_VEGA":              24,
	"CT_SERVER_SYMANTEC_WS_SIRIUS":            37,
	"CT_SERVER_SYMANTEC_WS_DENEB":             32,
	"CT_SERVER_COMODO_DODO":                   35,
	"CT_SERVER_COMODO_MAMMOTH":                36,
	"CT_SERVER_COMODO_SABRE":                  41,
	"CT_SERVER_WOSIGN_CTLOG":                  25,
	"CT_SERVER_WOSIGN_CT":                     26,
	"CT_SERVER_WOTRUS_CTLOG":                  47,
	"CT_SERVER_WOTRUS_CTLOG3":                 48,
	"CT_SERVER_STARTSSL_CT":                   29,
	"CT_SERVER_GDCA_CT":                       28,
	"CT_SERVER_GDCA_CTLOG":                    34,
	"CT_SERVER_GDCA_LOG":                      45,
	"CT_SERVER_GDCA_LOG2":                     46,
	"CT_SERVER_VENAFI_API_CTLOG":              31,
	"CT_SERVER_VENAFI_API_CTLOG_GEN2":         39,
	"CT_SERVER_NORDU_CT_PLAUSIBLE":            33,
	"CT_SERVER_LETSENCRYPT_CT_CLICKY":         43,
	"CT_SERVER_CERTLY_LOG":                    30,
	"CT_SERVER_CNNIC_CTSERVER":                27,
	"CT_SERVER_CERTIFICATETRANSPARENCY_CN_CT": 38,
	"CT_SERVER_SHECA_CT":                      42,
	"CT_SERVER_BEHIND_THE_SOFA":               44,
}

func (x CTServer) String() string {
	return proto.EnumName(CTServer_name, int32(x))
}
func (CTServer) EnumDescriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

type CTServerStatus struct {
	Index int64 `protobuf:"varint,1,opt,name=index" json:"index,omitempty"`
	// parsed out timestamp inside the SCT
	CtTimestamp int64 `protobuf:"varint,2,opt,name=ct_timestamp,json=ctTimestamp" json:"ct_timestamp,omitempty"`
	// when we found the certificate in CT
	PullTimestamp int64 `protobuf:"varint,3,opt,name=pull_timestamp,json=pullTimestamp" json:"pull_timestamp,omitempty"`
	// when we pushed the record to CT
	PushTimestamp int64        `protobuf:"varint,4,opt,name=push_timestamp,json=pushTimestamp" json:"push_timestamp,omitempty"`
	PushStatus    CTPushStatus `protobuf:"varint,5,opt,name=push_status,json=pushStatus,enum=zsearch.CTPushStatus" json:"push_status,omitempty"`
	Sct           []byte       `protobuf:"bytes,6,opt,name=sct,proto3" json:"sct,omitempty"`
	PushError     string       `protobuf:"bytes,7,opt,name=push_error,json=pushError" json:"push_error,omitempty"`
}

func (m *CTServerStatus) Reset()                    { *m = CTServerStatus{} }
func (m *CTServerStatus) String() string            { return proto.CompactTextString(m) }
func (*CTServerStatus) ProtoMessage()               {}
func (*CTServerStatus) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{0} }

func (m *CTServerStatus) GetIndex() int64 {
	if m != nil {
		return m.Index
	}
	return 0
}

func (m *CTServerStatus) GetCtTimestamp() int64 {
	if m != nil {
		return m.CtTimestamp
	}
	return 0
}

func (m *CTServerStatus) GetPullTimestamp() int64 {
	if m != nil {
		return m.PullTimestamp
	}
	return 0
}

func (m *CTServerStatus) GetPushTimestamp() int64 {
	if m != nil {
		return m.PushTimestamp
	}
	return 0
}

func (m *CTServerStatus) GetPushStatus() CTPushStatus {
	if m != nil {
		return m.PushStatus
	}
	return CTPushStatus_CT_PUSH_STATUS_RESERVED
}

func (m *CTServerStatus) GetSct() []byte {
	if m != nil {
		return m.Sct
	}
	return nil
}

func (m *CTServerStatus) GetPushError() string {
	if m != nil {
		return m.PushError
	}
	return ""
}

type CTStatus struct {
	CensysDev                   *CTServerStatus `protobuf:"bytes,1,opt,name=censys_dev,json=censysDev" json:"censys_dev,omitempty"`
	Censys                      *CTServerStatus `protobuf:"bytes,2,opt,name=censys" json:"censys,omitempty"`
	GoogleAviator               *CTServerStatus `protobuf:"bytes,10,opt,name=google_aviator,json=googleAviator" json:"google_aviator,omitempty"`
	GooglePilot                 *CTServerStatus `protobuf:"bytes,11,opt,name=google_pilot,json=googlePilot" json:"google_pilot,omitempty"`
	GoogleRocketeer             *CTServerStatus `protobuf:"bytes,12,opt,name=google_rocketeer,json=googleRocketeer" json:"google_rocketeer,omitempty"`
	GoogleSubmariner            *CTServerStatus `protobuf:"bytes,13,opt,name=google_submariner,json=googleSubmariner" json:"google_submariner,omitempty"`
	GoogleTesttube              *CTServerStatus `protobuf:"bytes,14,opt,name=google_testtube,json=googleTesttube" json:"google_testtube,omitempty"`
	GoogleIcarus                *CTServerStatus `protobuf:"bytes,15,opt,name=google_icarus,json=googleIcarus" json:"google_icarus,omitempty"`
	GoogleSkydiver              *CTServerStatus `protobuf:"bytes,16,opt,name=google_skydiver,json=googleSkydiver" json:"google_skydiver,omitempty"`
	GoogleDaedalus              *CTServerStatus `protobuf:"bytes,17,opt,name=google_daedalus,json=googleDaedalus" json:"google_daedalus,omitempty"`
	GoogleArgon_2017            *CTServerStatus `protobuf:"bytes,50,opt,name=google_argon_2017,json=googleArgon2017" json:"google_argon_2017,omitempty"`
	GoogleArgon_2018            *CTServerStatus `protobuf:"bytes,51,opt,name=google_argon_2018,json=googleArgon2018" json:"google_argon_2018,omitempty"`
	GoogleArgon_2019            *CTServerStatus `protobuf:"bytes,52,opt,name=google_argon_2019,json=googleArgon2019" json:"google_argon_2019,omitempty"`
	GoogleArgon_2020            *CTServerStatus `protobuf:"bytes,53,opt,name=google_argon_2020,json=googleArgon2020" json:"google_argon_2020,omitempty"`
	GoogleArgon_2021            *CTServerStatus `protobuf:"bytes,54,opt,name=google_argon_2021,json=googleArgon2021" json:"google_argon_2021,omitempty"`
	CloudflareNimbus_2017       *CTServerStatus `protobuf:"bytes,60,opt,name=cloudflare_nimbus_2017,json=cloudflareNimbus2017" json:"cloudflare_nimbus_2017,omitempty"`
	CloudflareNimbus_2018       *CTServerStatus `protobuf:"bytes,61,opt,name=cloudflare_nimbus_2018,json=cloudflareNimbus2018" json:"cloudflare_nimbus_2018,omitempty"`
	CloudflareNimbus_2019       *CTServerStatus `protobuf:"bytes,62,opt,name=cloudflare_nimbus_2019,json=cloudflareNimbus2019" json:"cloudflare_nimbus_2019,omitempty"`
	CloudflareNimbus_2020       *CTServerStatus `protobuf:"bytes,63,opt,name=cloudflare_nimbus_2020,json=cloudflareNimbus2020" json:"cloudflare_nimbus_2020,omitempty"`
	CloudflareNimbus_2021       *CTServerStatus `protobuf:"bytes,64,opt,name=cloudflare_nimbus_2021,json=cloudflareNimbus2021" json:"cloudflare_nimbus_2021,omitempty"`
	DigicertCt1                 *CTServerStatus `protobuf:"bytes,20,opt,name=digicert_ct1,json=digicertCt1" json:"digicert_ct1,omitempty"`
	DigicertCt2                 *CTServerStatus `protobuf:"bytes,40,opt,name=digicert_ct2,json=digicertCt2" json:"digicert_ct2,omitempty"`
	IzenpeComCt                 *CTServerStatus `protobuf:"bytes,21,opt,name=izenpe_com_ct,json=izenpeComCt" json:"izenpe_com_ct,omitempty"`
	IzenpeEusCt                 *CTServerStatus `protobuf:"bytes,22,opt,name=izenpe_eus_ct,json=izenpeEusCt" json:"izenpe_eus_ct,omitempty"`
	SymantecWsCt                *CTServerStatus `protobuf:"bytes,23,opt,name=symantec_ws_ct,json=symantecWsCt" json:"symantec_ws_ct,omitempty"`
	SymantecWsVega              *CTServerStatus `protobuf:"bytes,24,opt,name=symantec_ws_vega,json=symantecWsVega" json:"symantec_ws_vega,omitempty"`
	SymantecWsSirius            *CTServerStatus `protobuf:"bytes,37,opt,name=symantec_ws_sirius,json=symantecWsSirius" json:"symantec_ws_sirius,omitempty"`
	SymantecWsDeneb             *CTServerStatus `protobuf:"bytes,32,opt,name=symantec_ws_deneb,json=symantecWsDeneb" json:"symantec_ws_deneb,omitempty"`
	ComodoDodo                  *CTServerStatus `protobuf:"bytes,34,opt,name=comodo_dodo,json=comodoDodo" json:"comodo_dodo,omitempty"`
	ComodoMammoth               *CTServerStatus `protobuf:"bytes,35,opt,name=comodo_mammoth,json=comodoMammoth" json:"comodo_mammoth,omitempty"`
	ComodoSabre                 *CTServerStatus `protobuf:"bytes,41,opt,name=comodo_sabre,json=comodoSabre" json:"comodo_sabre,omitempty"`
	WosignCtlog                 *CTServerStatus `protobuf:"bytes,25,opt,name=wosign_ctlog,json=wosignCtlog" json:"wosign_ctlog,omitempty"`
	WosignCt                    *CTServerStatus `protobuf:"bytes,26,opt,name=wosign_ct,json=wosignCt" json:"wosign_ct,omitempty"`
	WotrusCtlog                 *CTServerStatus `protobuf:"bytes,47,opt,name=wotrus_ctlog,json=wotrusCtlog" json:"wotrus_ctlog,omitempty"`
	WotrusCtlog3                *CTServerStatus `protobuf:"bytes,48,opt,name=wotrus_ctlog3,json=wotrusCtlog3" json:"wotrus_ctlog3,omitempty"`
	GdcaCt                      *CTServerStatus `protobuf:"bytes,28,opt,name=gdca_ct,json=gdcaCt" json:"gdca_ct,omitempty"`
	GdcaCtlog                   *CTServerStatus `protobuf:"bytes,36,opt,name=gdca_ctlog,json=gdcaCtlog" json:"gdca_ctlog,omitempty"`
	GdcaLog                     *CTServerStatus `protobuf:"bytes,45,opt,name=gdca_log,json=gdcaLog" json:"gdca_log,omitempty"`
	GdcaLog2                    *CTServerStatus `protobuf:"bytes,46,opt,name=gdca_log2,json=gdcaLog2" json:"gdca_log2,omitempty"`
	VenafiApiCtlog              *CTServerStatus `protobuf:"bytes,31,opt,name=venafi_api_ctlog,json=venafiApiCtlog" json:"venafi_api_ctlog,omitempty"`
	VenafiApiCtlogGen2          *CTServerStatus `protobuf:"bytes,39,opt,name=venafi_api_ctlog_gen2,json=venafiApiCtlogGen2" json:"venafi_api_ctlog_gen2,omitempty"`
	NorduCtPlausible            *CTServerStatus `protobuf:"bytes,33,opt,name=nordu_ct_plausible,json=norduCtPlausible" json:"nordu_ct_plausible,omitempty"`
	CnnicCtserver               *CTServerStatus `protobuf:"bytes,27,opt,name=cnnic_ctserver,json=cnnicCtserver" json:"cnnic_ctserver,omitempty"`
	StartsslCt                  *CTServerStatus `protobuf:"bytes,29,opt,name=startssl_ct,json=startsslCt" json:"startssl_ct,omitempty"`
	CertlyLog                   *CTServerStatus `protobuf:"bytes,30,opt,name=certly_log,json=certlyLog" json:"certly_log,omitempty"`
	ShecaCt                     *CTServerStatus `protobuf:"bytes,42,opt,name=sheca_ct,json=shecaCt" json:"sheca_ct,omitempty"`
	LetsencryptCtClicky         *CTServerStatus `protobuf:"bytes,43,opt,name=letsencrypt_ct_clicky,json=letsencryptCtClicky" json:"letsencrypt_ct_clicky,omitempty"`
	BehindTheSofa               *CTServerStatus `protobuf:"bytes,44,opt,name=behind_the_sofa,json=behindTheSofa" json:"behind_the_sofa,omitempty"`
	CertificatetransparencyCnCt *CTServerStatus `protobuf:"bytes,38,opt,name=certificatetransparency_cn_ct,json=certificatetransparencyCnCt" json:"certificatetransparency_cn_ct,omitempty"`
}

func (m *CTStatus) Reset()                    { *m = CTStatus{} }
func (m *CTStatus) String() string            { return proto.CompactTextString(m) }
func (*CTStatus) ProtoMessage()               {}
func (*CTStatus) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{1} }

func (m *CTStatus) GetCensysDev() *CTServerStatus {
	if m != nil {
		return m.CensysDev
	}
	return nil
}

func (m *CTStatus) GetCensys() *CTServerStatus {
	if m != nil {
		return m.Censys
	}
	return nil
}

func (m *CTStatus) GetGoogleAviator() *CTServerStatus {
	if m != nil {
		return m.GoogleAviator
	}
	return nil
}

func (m *CTStatus) GetGooglePilot() *CTServerStatus {
	if m != nil {
		return m.GooglePilot
	}
	return nil
}

func (m *CTStatus) GetGoogleRocketeer() *CTServerStatus {
	if m != nil {
		return m.GoogleRocketeer
	}
	return nil
}

func (m *CTStatus) GetGoogleSubmariner() *CTServerStatus {
	if m != nil {
		return m.GoogleSubmariner
	}
	return nil
}

func (m *CTStatus) GetGoogleTesttube() *CTServerStatus {
	if m != nil {
		return m.GoogleTesttube
	}
	return nil
}

func (m *CTStatus) GetGoogleIcarus() *CTServerStatus {
	if m != nil {
		return m.GoogleIcarus
	}
	return nil
}

func (m *CTStatus) GetGoogleSkydiver() *CTServerStatus {
	if m != nil {
		return m.GoogleSkydiver
	}
	return nil
}

func (m *CTStatus) GetGoogleDaedalus() *CTServerStatus {
	if m != nil {
		return m.GoogleDaedalus
	}
	return nil
}

func (m *CTStatus) GetGoogleArgon_2017() *CTServerStatus {
	if m != nil {
		return m.GoogleArgon_2017
	}
	return nil
}

func (m *CTStatus) GetGoogleArgon_2018() *CTServerStatus {
	if m != nil {
		return m.GoogleArgon_2018
	}
	return nil
}

func (m *CTStatus) GetGoogleArgon_2019() *CTServerStatus {
	if m != nil {
		return m.GoogleArgon_2019
	}
	return nil
}

func (m *CTStatus) GetGoogleArgon_2020() *CTServerStatus {
	if m != nil {
		return m.GoogleArgon_2020
	}
	return nil
}

func (m *CTStatus) GetGoogleArgon_2021() *CTServerStatus {
	if m != nil {
		return m.GoogleArgon_2021
	}
	return nil
}

func (m *CTStatus) GetCloudflareNimbus_2017() *CTServerStatus {
	if m != nil {
		return m.CloudflareNimbus_2017
	}
	return nil
}

func (m *CTStatus) GetCloudflareNimbus_2018() *CTServerStatus {
	if m != nil {
		return m.CloudflareNimbus_2018
	}
	return nil
}

func (m *CTStatus) GetCloudflareNimbus_2019() *CTServerStatus {
	if m != nil {
		return m.CloudflareNimbus_2019
	}
	return nil
}

func (m *CTStatus) GetCloudflareNimbus_2020() *CTServerStatus {
	if m != nil {
		return m.CloudflareNimbus_2020
	}
	return nil
}

func (m *CTStatus) GetCloudflareNimbus_2021() *CTServerStatus {
	if m != nil {
		return m.CloudflareNimbus_2021
	}
	return nil
}

func (m *CTStatus) GetDigicertCt1() *CTServerStatus {
	if m != nil {
		return m.DigicertCt1
	}
	return nil
}

func (m *CTStatus) GetDigicertCt2() *CTServerStatus {
	if m != nil {
		return m.DigicertCt2
	}
	return nil
}

func (m *CTStatus) GetIzenpeComCt() *CTServerStatus {
	if m != nil {
		return m.IzenpeComCt
	}
	return nil
}

func (m *CTStatus) GetIzenpeEusCt() *CTServerStatus {
	if m != nil {
		return m.IzenpeEusCt
	}
	return nil
}

func (m *CTStatus) GetSymantecWsCt() *CTServerStatus {
	if m != nil {
		return m.SymantecWsCt
	}
	return nil
}

func (m *CTStatus) GetSymantecWsVega() *CTServerStatus {
	if m != nil {
		return m.SymantecWsVega
	}
	return nil
}

func (m *CTStatus) GetSymantecWsSirius() *CTServerStatus {
	if m != nil {
		return m.SymantecWsSirius
	}
	return nil
}

func (m *CTStatus) GetSymantecWsDeneb() *CTServerStatus {
	if m != nil {
		return m.SymantecWsDeneb
	}
	return nil
}

func (m *CTStatus) GetComodoDodo() *CTServerStatus {
	if m != nil {
		return m.ComodoDodo
	}
	return nil
}

func (m *CTStatus) GetComodoMammoth() *CTServerStatus {
	if m != nil {
		return m.ComodoMammoth
	}
	return nil
}

func (m *CTStatus) GetComodoSabre() *CTServerStatus {
	if m != nil {
		return m.ComodoSabre
	}
	return nil
}

func (m *CTStatus) GetWosignCtlog() *CTServerStatus {
	if m != nil {
		return m.WosignCtlog
	}
	return nil
}

func (m *CTStatus) GetWosignCt() *CTServerStatus {
	if m != nil {
		return m.WosignCt
	}
	return nil
}

func (m *CTStatus) GetWotrusCtlog() *CTServerStatus {
	if m != nil {
		return m.WotrusCtlog
	}
	return nil
}

func (m *CTStatus) GetWotrusCtlog3() *CTServerStatus {
	if m != nil {
		return m.WotrusCtlog3
	}
	return nil
}

func (m *CTStatus) GetGdcaCt() *CTServerStatus {
	if m != nil {
		return m.GdcaCt
	}
	return nil
}

func (m *CTStatus) GetGdcaCtlog() *CTServerStatus {
	if m != nil {
		return m.GdcaCtlog
	}
	return nil
}

func (m *CTStatus) GetGdcaLog() *CTServerStatus {
	if m != nil {
		return m.GdcaLog
	}
	return nil
}

func (m *CTStatus) GetGdcaLog2() *CTServerStatus {
	if m != nil {
		return m.GdcaLog2
	}
	return nil
}

func (m *CTStatus) GetVenafiApiCtlog() *CTServerStatus {
	if m != nil {
		return m.VenafiApiCtlog
	}
	return nil
}

func (m *CTStatus) GetVenafiApiCtlogGen2() *CTServerStatus {
	if m != nil {
		return m.VenafiApiCtlogGen2
	}
	return nil
}

func (m *CTStatus) GetNorduCtPlausible() *CTServerStatus {
	if m != nil {
		return m.NorduCtPlausible
	}
	return nil
}

func (m *CTStatus) GetCnnicCtserver() *CTServerStatus {
	if m != nil {
		return m.CnnicCtserver
	}
	return nil
}

func (m *CTStatus) GetStartsslCt() *CTServerStatus {
	if m != nil {
		return m.StartsslCt
	}
	return nil
}

func (m *CTStatus) GetCertlyLog() *CTServerStatus {
	if m != nil {
		return m.CertlyLog
	}
	return nil
}

func (m *CTStatus) GetShecaCt() *CTServerStatus {
	if m != nil {
		return m.ShecaCt
	}
	return nil
}

func (m *CTStatus) GetLetsencryptCtClicky() *CTServerStatus {
	if m != nil {
		return m.LetsencryptCtClicky
	}
	return nil
}

func (m *CTStatus) GetBehindTheSofa() *CTServerStatus {
	if m != nil {
		return m.BehindTheSofa
	}
	return nil
}

func (m *CTStatus) GetCertificatetransparencyCnCt() *CTServerStatus {
	if m != nil {
		return m.CertificatetransparencyCnCt
	}
	return nil
}

type SCT struct {
	Sha256Fp []byte          `protobuf:"bytes,1,opt,name=sha256fp,proto3" json:"sha256fp,omitempty"`
	Server   CTServer        `protobuf:"varint,2,opt,name=server,enum=zsearch.CTServer" json:"server,omitempty"`
	Status   *CTServerStatus `protobuf:"bytes,3,opt,name=status" json:"status,omitempty"`
}

func (m *SCT) Reset()                    { *m = SCT{} }
func (m *SCT) String() string            { return proto.CompactTextString(m) }
func (*SCT) ProtoMessage()               {}
func (*SCT) Descriptor() ([]byte, []int) { return fileDescriptor4, []int{2} }

func (m *SCT) GetSha256Fp() []byte {
	if m != nil {
		return m.Sha256Fp
	}
	return nil
}

func (m *SCT) GetServer() CTServer {
	if m != nil {
		return m.Server
	}
	return CTServer_CT_SERVER_RESERVED
}

func (m *SCT) GetStatus() *CTServerStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func init() {
	proto.RegisterType((*CTServerStatus)(nil), "zsearch.CTServerStatus")
	proto.RegisterType((*CTStatus)(nil), "zsearch.CTStatus")
	proto.RegisterType((*SCT)(nil), "zsearch.SCT")
	proto.RegisterEnum("zsearch.CTPushStatus", CTPushStatus_name, CTPushStatus_value)
	proto.RegisterEnum("zsearch.CTServer", CTServer_name, CTServer_value)
}

func init() { proto.RegisterFile("ct.proto", fileDescriptor4) }

var fileDescriptor4 = []byte{
	// 1782 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x98, 0x7d, 0x53, 0xdb, 0x3a,
	0xf6, 0xc7, 0x7f, 0x94, 0x5b, 0xda, 0x8a, 0x87, 0x0a, 0x5d, 0x1e, 0x54, 0x28, 0x2d, 0xa5, 0xed,
	0x2d, 0x6d, 0xef, 0xa5, 0xc1, 0xb4, 0xfc, 0x60, 0xb7, 0x4f, 0x46, 0x56, 0xc1, 0x4b, 0x62, 0x67,
	0x2c, 0x07, 0x96, 0xdd, 0x3f, 0x34, 0xc6, 0x11, 0xc1, 0xd3, 0xc4, 0xce, 0xd8, 0x0e, 0x77, 0xb9,
	0x33, 0x3b, 0xb3, 0x2f, 0x63, 0xdf, 0xe3, 0xbe, 0x87, 0x9d, 0x1d, 0xd9, 0x0e, 0xd8, 0x34, 0xc4,
	0xf0, 0x1f, 0xd6, 0xf9, 0x7c, 0xbf, 0x3a, 0x3e, 0x47, 0x52, 0x2c, 0xc0, 0x7d, 0x37, 0x5e, 0xeb,
	0x86, 0x41, 0x1c, 0xa0, 0x7b, 0x7f, 0x44, 0xc2, 0x09, 0xdd, 0xd3, 0x95, 0x7f, 0xdd, 0x01, 0x53,
	0xc4, 0x66, 0x22, 0x3c, 0x13, 0x21, 0x8b, 0x9d, 0xb8, 0x17, 0xa1, 0x19, 0x70, 0xd7, 0xf3, 0x9b,
	0xe2, 0x1f, 0x78, 0x64, 0x79, 0x64, 0x75, 0xd4, 0x4a, 0x1f, 0xd0, 0x33, 0x30, 0xe1, 0xc6, 0x3c,
	0xf6, 0x3a, 0x22, 0x8a, 0x9d, 0x4e, 0x17, 0xdf, 0x49, 0x82, 0xe3, 0x6e, 0x6c, 0xf7, 0x87, 0xd0,
	0x4b, 0x30, 0xd5, 0xed, 0xb5, 0xdb, 0x39, 0x68, 0x34, 0x81, 0x26, 0xe5, 0xe8, 0x15, 0x2c, 0x3a,
	0xcd, 0x61, 0x3f, 0xf5, 0xb1, 0xe8, 0xf4, 0x12, 0xdb, 0x04, 0xe3, 0x09, 0x16, 0x25, 0x59, 0xe1,
	0xbb, 0xcb, 0x23, 0xab, 0x53, 0xca, 0xec, 0x5a, 0x96, 0xf8, 0x1a, 0xb1, 0xeb, 0xbd, 0xe8, 0x34,
	0x4d, 0xd9, 0x02, 0xdd, 0x8b, 0xbf, 0x11, 0x04, 0xa3, 0x91, 0x1b, 0xe3, 0xb1, 0xe5, 0x91, 0xd5,
	0x09, 0x4b, 0xfe, 0x89, 0x96, 0x40, 0x12, 0xe7, 0x22, 0x0c, 0x83, 0x10, 0xdf, 0x5b, 0x1e, 0x59,
	0x7d, 0x60, 0x3d, 0x90, 0x23, 0x54, 0x0e, 0xac, 0xfc, 0x17, 0x83, 0xfb, 0xc4, 0xce, 0xd4, 0x9b,
	0x00, 0xb8, 0xc2, 0x8f, 0xce, 0x23, 0xde, 0x14, 0x67, 0x49, 0x05, 0xc6, 0x95, 0xf9, 0xdc, 0xa4,
	0xf9, 0x4a, 0x59, 0x0f, 0x52, 0x54, 0x13, 0x67, 0xe8, 0x1d, 0x18, 0x4b, 0x1f, 0x92, 0xc2, 0x0c,
	0xd1, 0x64, 0x18, 0xfa, 0x0c, 0xa6, 0x5a, 0x41, 0xd0, 0x6a, 0x0b, 0xee, 0x9c, 0x79, 0x4e, 0x1c,
	0x84, 0x18, 0x0c, 0x17, 0x4e, 0xa6, 0xb8, 0x9a, 0xd2, 0xe8, 0x4f, 0x60, 0x22, 0xd3, 0x77, 0xbd,
	0x76, 0x10, 0xe3, 0xf1, 0xe1, 0xea, 0xf1, 0x14, 0xae, 0x4b, 0x16, 0xed, 0x00, 0x98, 0x69, 0xc3,
	0xc0, 0xfd, 0x2e, 0x62, 0x21, 0x42, 0x3c, 0x31, 0x5c, 0xff, 0x30, 0x15, 0x58, 0x7d, 0x1e, 0x69,
	0x60, 0x3a, 0xf3, 0x88, 0x7a, 0xc7, 0x1d, 0x27, 0xf4, 0x7c, 0x11, 0xe2, 0xc9, 0xe1, 0x26, 0xd9,
	0xac, 0xec, 0x42, 0x80, 0xbe, 0x82, 0xcc, 0x98, 0xc7, 0x22, 0x8a, 0xe3, 0xde, 0xb1, 0xc0, 0x53,
	0xc3, 0x3d, 0xb2, 0xaa, 0xd9, 0x19, 0x8e, 0x3e, 0x82, 0xac, 0x30, 0xdc, 0x73, 0x9d, 0xb0, 0x17,
	0xe1, 0x87, 0xc3, 0xf5, 0x59, 0xd5, 0xf4, 0x04, 0xce, 0xcd, 0x1f, 0x7d, 0x3f, 0x6f, 0x7a, 0x67,
	0x22, 0xc4, 0xf0, 0x46, 0xf3, 0xb3, 0x0c, 0xcf, 0x39, 0x34, 0x1d, 0xd1, 0x74, 0xda, 0xbd, 0x08,
	0x4f, 0xdf, 0xc8, 0x41, 0xcb, 0x70, 0x44, 0x2e, 0x2a, 0xe9, 0x84, 0xad, 0xc0, 0xe7, 0x4a, 0x65,
	0xfd, 0xff, 0xb1, 0x72, 0xa3, 0x76, 0xa8, 0x52, 0x20, 0xf9, 0x41, 0x26, 0x5b, 0x78, 0xe3, 0x56,
	0x26, 0x5b, 0x83, 0x4c, 0xb6, 0xf1, 0xfb, 0x5b, 0x99, 0x6c, 0x0f, 0x30, 0x51, 0x2a, 0xf8, 0xc3,
	0x6d, 0x4c, 0x94, 0xca, 0x20, 0x93, 0x75, 0xbc, 0x79, 0x2b, 0x93, 0x75, 0x54, 0x03, 0x73, 0x6e,
	0x3b, 0xe8, 0x35, 0x4f, 0xda, 0x4e, 0x28, 0xb8, 0xef, 0x75, 0x8e, 0x7b, 0x51, 0x5a, 0xdd, 0x8f,
	0xc3, 0x9d, 0x66, 0x2e, 0x65, 0x46, 0xa2, 0x4a, 0x4a, 0x7c, 0x9d, 0xdd, 0x16, 0xfe, 0x74, 0x7b,
	0xbb, 0xad, 0x6b, 0xed, 0xb6, 0xf1, 0xe7, 0xdb, 0xdb, 0x6d, 0x5f, 0x67, 0xa7, 0x54, 0xf0, 0x97,
	0x5b, 0xdb, 0x29, 0x95, 0x6b, 0xed, 0xd6, 0xf1, 0xd7, 0xdb, 0xdb, 0xad, 0xcb, 0xd3, 0xaa, 0xe9,
	0xb5, 0x3c, 0x57, 0x84, 0x31, 0x77, 0xe3, 0x75, 0x3c, 0x53, 0x72, 0x5a, 0xf5, 0x61, 0x12, 0x5f,
	0xd5, 0x2a, 0x78, 0xf5, 0xc6, 0x5a, 0x05, 0xfd, 0x19, 0x4c, 0x7a, 0x7f, 0x08, 0xbf, 0x2b, 0xb8,
	0x1b, 0x74, 0xb8, 0x1b, 0xe3, 0xd9, 0x12, 0x71, 0x4a, 0x93, 0xa0, 0x43, 0xe2, 0x9c, 0x58, 0xf4,
	0x22, 0x29, 0x9e, 0xbb, 0x91, 0x98, 0xf6, 0x22, 0x12, 0xa3, 0x4f, 0x60, 0x2a, 0x3a, 0xef, 0x38,
	0x7e, 0x2c, 0x5c, 0xfe, 0x7b, 0xa2, 0x9e, 0x2f, 0x39, 0x98, 0xfa, 0xf8, 0xa1, 0x94, 0xab, 0x00,
	0xe6, 0xe5, 0x67, 0xa2, 0xe5, 0x60, 0x5c, 0x72, 0xae, 0x5c, 0x1a, 0x1c, 0x88, 0x96, 0x83, 0x28,
	0x40, 0x79, 0x8b, 0xc8, 0x0b, 0xbd, 0x5e, 0x84, 0x5f, 0x96, 0x1c, 0xd1, 0x97, 0x26, 0x2c, 0x11,
	0xc8, 0xad, 0x98, 0xb7, 0x69, 0x0a, 0x5f, 0x1c, 0xe3, 0xe5, 0x92, 0xad, 0x78, 0xe9, 0xa2, 0x49,
	0x1e, 0x6d, 0x81, 0x71, 0x37, 0xe8, 0x04, 0xcd, 0x80, 0x37, 0x83, 0x66, 0x80, 0x57, 0x86, 0xcb,
	0x41, 0xca, 0x6a, 0x41, 0x33, 0x90, 0xbf, 0x93, 0x99, 0xb2, 0xe3, 0x74, 0x3a, 0x41, 0x7c, 0x8a,
	0x9f, 0x97, 0xfc, 0x4e, 0xa6, 0x78, 0x2d, 0xa5, 0xe5, 0xea, 0xc9, 0xf4, 0x91, 0x73, 0x1c, 0x0a,
	0xfc, 0xba, 0xa4, 0x87, 0x29, 0xcc, 0x24, 0x2b, 0xb5, 0xbf, 0x07, 0x91, 0xd7, 0xf2, 0xb9, 0x1b,
	0xb7, 0x83, 0x16, 0x7e, 0x54, 0xa2, 0x4d, 0x61, 0x22, 0x59, 0xf4, 0x1e, 0x3c, 0xb8, 0xd0, 0xe2,
	0x85, 0xe1, 0xc2, 0xfb, 0x7d, 0x61, 0x3a, 0x63, 0x1c, 0x26, 0xcb, 0x4d, 0xce, 0xf8, 0xae, 0x74,
	0x46, 0x09, 0xa7, 0x33, 0x7e, 0x04, 0x93, 0x79, 0xed, 0x06, 0xae, 0x94, 0x2c, 0xb8, 0x9c, 0x78,
	0x03, 0x55, 0xc0, 0xbd, 0x56, 0xd3, 0x75, 0x64, 0xb6, 0x8f, 0x4b, 0xbe, 0x60, 0x24, 0x47, 0x62,
	0xf9, 0xa9, 0x94, 0x29, 0x64, 0xa6, 0x2f, 0x4a, 0x3e, 0x95, 0x52, 0x91, 0xcc, 0x53, 0x01, 0xf7,
	0x13, 0x9d, 0x54, 0xfd, 0x36, 0x5c, 0x95, 0xa4, 0x54, 0x4d, 0xab, 0xd9, 0xd7, 0x28, 0x78, 0xad,
	0xa4, 0x9a, 0x99, 0x48, 0x91, 0x9b, 0xe8, 0x4c, 0xf8, 0xce, 0x89, 0xc7, 0x9d, 0xae, 0x97, 0xe5,
	0xf9, 0xb4, 0x64, 0x13, 0xa5, 0x02, 0xb5, 0xeb, 0xa5, 0xc9, 0xfe, 0x05, 0xcc, 0x5e, 0xb5, 0xe0,
	0x2d, 0xe1, 0x2b, 0xf8, 0xd5, 0x70, 0x1f, 0x54, 0xf4, 0xd9, 0x15, 0xbe, 0x22, 0x37, 0xa4, 0x1f,
	0x84, 0xcd, 0x1e, 0x77, 0x63, 0xde, 0x6d, 0x3b, 0xbd, 0xc8, 0x3b, 0x6e, 0x0b, 0xfc, 0xac, 0x64,
	0x43, 0x26, 0x12, 0x12, 0xd7, 0xfb, 0x82, 0x64, 0x47, 0xf8, 0xbe, 0xe7, 0x72, 0x37, 0x8e, 0x12,
	0x12, 0x2f, 0x96, 0xed, 0x08, 0x89, 0x93, 0x8c, 0x96, 0x7b, 0x31, 0x8a, 0x9d, 0x30, 0x8e, 0xa2,
	0xb6, 0xec, 0xf6, 0x52, 0xc9, 0x5e, 0xec, 0xb3, 0x69, 0xc7, 0xe5, 0xc1, 0xda, 0x3e, 0x4f, 0x7a,
	0xf7, 0xa4, 0xf4, 0xe3, 0x58, 0xa2, 0xd5, 0xb4, 0xe3, 0xd1, 0xa9, 0x48, 0x17, 0xd7, 0x9b, 0x92,
	0x8e, 0x27, 0x20, 0x89, 0xd1, 0x3e, 0x98, 0x6d, 0x8b, 0x38, 0x12, 0xbe, 0x1b, 0x9e, 0x77, 0xe5,
	0xc1, 0xcf, 0xdd, 0xb6, 0xe7, 0x7e, 0x3f, 0xc7, 0x6f, 0x87, 0x1b, 0xfc, 0x9c, 0x53, 0x91, 0x98,
	0x24, 0x1a, 0xf4, 0x05, 0x3c, 0x3c, 0x16, 0xa7, 0x9e, 0xdf, 0xe4, 0xf1, 0xa9, 0xe0, 0x51, 0x70,
	0xe2, 0xe0, 0x5f, 0x4b, 0x6a, 0x96, 0xf2, 0xf6, 0xa9, 0x60, 0xc1, 0x89, 0x83, 0xfe, 0x0e, 0x96,
	0xe4, 0xeb, 0x78, 0x27, 0x9e, 0xeb, 0xc4, 0x22, 0x0e, 0x1d, 0x3f, 0xea, 0x3a, 0xa1, 0xf0, 0xdd,
	0x73, 0xee, 0x26, 0x3b, 0xfc, 0x97, 0xe1, 0x76, 0x8b, 0xd7, 0xa8, 0x89, 0x4f, 0xe2, 0x95, 0x7f,
	0x82, 0x51, 0x46, 0x6c, 0xb4, 0x20, 0xab, 0xe4, 0x28, 0x1f, 0x36, 0x4f, 0xba, 0xc9, 0xc5, 0x63,
	0xc2, 0xba, 0x78, 0x46, 0xaf, 0xc1, 0x58, 0xd6, 0xeb, 0x3b, 0xc9, 0x3d, 0x68, 0xfa, 0x87, 0x89,
	0xac, 0x0c, 0x90, 0x37, 0x91, 0xec, 0xca, 0x34, 0x5a, 0xb2, 0x8f, 0x53, 0xec, 0xcd, 0x7f, 0x46,
	0xc0, 0x44, 0xfe, 0x36, 0x85, 0x16, 0xc1, 0x3c, 0xb1, 0x79, 0xbd, 0xc1, 0xf6, 0x38, 0xb3, 0x55,
	0xbb, 0xc1, 0xb8, 0x45, 0x19, 0xb5, 0x0e, 0xa8, 0x06, 0xff, 0x0f, 0x2d, 0x80, 0xb9, 0x2b, 0xc1,
	0x86, 0xb1, 0x6f, 0x98, 0x87, 0x06, 0x1c, 0x19, 0x10, 0x63, 0x0d, 0x42, 0x28, 0x63, 0xf0, 0x0e,
	0x5a, 0x06, 0x8f, 0x07, 0xeb, 0x38, 0xb5, 0x2c, 0xd3, 0x82, 0xa3, 0xe8, 0x29, 0x58, 0xbc, 0x42,
	0xe8, 0xc6, 0x81, 0x5a, 0xd5, 0x35, 0x6e, 0x99, 0xa6, 0x0d, 0x7f, 0x42, 0xcf, 0xc0, 0xd2, 0x15,
	0x40, 0xad, 0x5a, 0x54, 0xd5, 0x8e, 0x38, 0xfd, 0xab, 0xce, 0x6c, 0x06, 0xef, 0x0e, 0x98, 0xe5,
	0x50, 0xaf, 0x56, 0xb9, 0x61, 0xa6, 0x83, 0x70, 0xec, 0xcd, 0xbf, 0x27, 0x92, 0xdb, 0x5e, 0x5a,
	0xab, 0x39, 0x80, 0x88, 0xcd, 0x93, 0x77, 0xb3, 0xf2, 0x2f, 0x99, 0xda, 0x64, 0xe3, 0x84, 0x1a,
	0xec, 0x88, 0x71, 0x8d, 0x1e, 0xd0, 0xaa, 0x59, 0xaf, 0x51, 0xc3, 0x86, 0x23, 0x59, 0xb2, 0x45,
	0xa2, 0x6e, 0x99, 0x5a, 0x83, 0xd8, 0xba, 0x69, 0xc0, 0x3b, 0xe8, 0x31, 0xc0, 0x97, 0xc0, 0xae,
	0x69, 0xee, 0x56, 0x29, 0x57, 0x0f, 0x74, 0xd5, 0x36, 0x2d, 0x08, 0xb2, 0x4a, 0x15, 0xa3, 0x75,
	0xbd, 0x6a, 0xda, 0x70, 0x1c, 0x3d, 0x01, 0x0b, 0x3f, 0xc4, 0x2c, 0x93, 0xec, 0x53, 0x9b, 0x52,
	0x0b, 0x4e, 0x14, 0xa7, 0xce, 0xe2, 0xac, 0xb1, 0x53, 0x53, 0x2d, 0xdd, 0xa0, 0x16, 0x9c, 0x44,
	0x4b, 0xe0, 0xd1, 0x0f, 0x80, 0x4d, 0x99, 0x6d, 0x37, 0x76, 0x28, 0x9c, 0xca, 0xda, 0x5b, 0x0c,
	0xeb, 0x44, 0xb5, 0x1a, 0x0c, 0x3e, 0x1c, 0xa8, 0x65, 0xfb, 0x47, 0x9a, 0x7e, 0x40, 0x2d, 0x08,
	0x07, 0x86, 0x35, 0x95, 0x6a, 0x6a, 0xb5, 0xc1, 0xe0, 0xf4, 0xc0, 0xd4, 0x54, 0x6b, 0xd7, 0x34,
	0x92, 0xcf, 0x6e, 0xa8, 0x0c, 0x07, 0xb6, 0xe0, 0xc6, 0x70, 0x60, 0x1b, 0xbe, 0x1f, 0x0a, 0x28,
	0x15, 0xf8, 0x61, 0x38, 0xb0, 0x0e, 0x37, 0xd1, 0x0b, 0xb0, 0x9c, 0x6b, 0x5d, 0xd5, 0x6c, 0x68,
	0xdf, 0xaa, 0xaa, 0x45, 0xb9, 0xa1, 0xd7, 0x76, 0x1a, 0x2c, 0xcd, 0xf4, 0xe3, 0x0d, 0xa8, 0x2d,
	0xf8, 0xe9, 0x06, 0xd4, 0x36, 0xfc, 0x5c, 0x4e, 0x29, 0x15, 0xf8, 0xe5, 0x06, 0xd4, 0x3a, 0xfc,
	0x5a, 0x5c, 0x39, 0x9a, 0xbe, 0xab, 0x13, 0x6a, 0xd9, 0x9c, 0xd8, 0xeb, 0x70, 0xe6, 0xda, 0x98,
	0x02, 0x57, 0x8b, 0x5d, 0xd7, 0xff, 0x46, 0x8d, 0x3a, 0xe5, 0xc4, 0xac, 0x71, 0x62, 0xc3, 0xd9,
	0x81, 0x41, 0xda, 0x60, 0x32, 0x38, 0x57, 0x5c, 0xc9, 0xec, 0xa8, 0xa6, 0x1a, 0x36, 0x25, 0xfc,
	0x30, 0x89, 0xce, 0x17, 0x57, 0x6b, 0x3e, 0x7a, 0x40, 0x77, 0x55, 0x88, 0x8b, 0x5b, 0x29, 0x1f,
	0x67, 0xba, 0xa5, 0x37, 0x18, 0x7c, 0x59, 0x6c, 0x58, 0x9e, 0xd0, 0xa8, 0x41, 0x77, 0xe0, 0x32,
	0x7a, 0x04, 0x66, 0x73, 0x85, 0x31, 0x6b, 0xa6, 0x66, 0x72, 0xcd, 0xd4, 0x4c, 0xf8, 0xbc, 0x98,
	0x5b, 0x16, 0xaa, 0xa9, 0xb5, 0x9a, 0x69, 0xef, 0xc1, 0x17, 0xc5, 0x7a, 0x64, 0x51, 0xa6, 0xee,
	0x58, 0x14, 0xbe, 0x2e, 0xc6, 0x0e, 0x4d, 0xa6, 0xef, 0x1a, 0x9c, 0xd8, 0x55, 0x73, 0x17, 0x3e,
	0x42, 0xf3, 0xe0, 0xe7, 0x01, 0x31, 0xb8, 0x70, 0x55, 0x64, 0x5b, 0x49, 0x8d, 0xa4, 0xe8, 0x5d,
	0xb1, 0x86, 0xf9, 0xd8, 0x06, 0xac, 0x14, 0x5f, 0x81, 0xd9, 0xaa, 0x65, 0x33, 0x56, 0x95, 0x9e,
	0x4b, 0x68, 0x16, 0x4c, 0xe7, 0xd6, 0xab, 0x46, 0x54, 0x39, 0xfc, 0x18, 0x61, 0x30, 0xf3, 0xc3,
	0xb0, 0x9c, 0x68, 0xa5, 0x78, 0x68, 0x25, 0x11, 0x39, 0xfe, 0x5b, 0x31, 0xeb, 0xfe, 0xb8, 0x02,
	0xd7, 0x8a, 0x2d, 0x3a, 0xa0, 0x86, 0xfa, 0x4d, 0xe7, 0x6a, 0x5d, 0xcf, 0x0c, 0x9f, 0xa2, 0xe7,
	0xe0, 0xe9, 0xf5, 0x71, 0xbe, 0x4b, 0x0d, 0x05, 0xbe, 0x2a, 0xf6, 0xd1, 0x30, 0x2d, 0xad, 0xc1,
	0xe5, 0x49, 0x5b, 0x55, 0x1b, 0x4c, 0xdf, 0xa9, 0x52, 0xf8, 0xac, 0x68, 0x53, 0xa5, 0x36, 0xa3,
	0x06, 0xb1, 0x8e, 0xea, 0x72, 0x01, 0x72, 0x52, 0xd5, 0xc9, 0xfe, 0x11, 0x7c, 0x5b, 0x7c, 0x2d,
	0xb9, 0x3c, 0xab, 0x47, 0x49, 0xfa, 0x4f, 0xae, 0xb4, 0xd2, 0x30, 0x74, 0xc2, 0x89, 0x9d, 0x3e,
	0xc2, 0x45, 0xf4, 0x16, 0xbc, 0x2a, 0xea, 0xf4, 0x6f, 0x3a, 0x51, 0x6d, 0x6a, 0x5b, 0xaa, 0xc1,
	0xea, 0xaa, 0x45, 0x0d, 0x72, 0xc4, 0x49, 0xd2, 0xa6, 0x5f, 0x8a, 0x15, 0x62, 0x7b, 0x34, 0xad,
	0xe9, 0x9b, 0xe2, 0xe9, 0xb5, 0x43, 0xf7, 0x74, 0x43, 0xe3, 0xf6, 0x1e, 0xe5, 0xcc, 0xfc, 0xa6,
	0xc2, 0x5f, 0x8f, 0xc7, 0x92, 0xff, 0x8d, 0x6e, 0xfc, 0x2f, 0x00, 0x00, 0xff, 0xff, 0xb0, 0x52,
	0xe5, 0x97, 0x27, 0x15, 0x00, 0x00,
}
